= stacksaga-Kafka-starter

`stacksaga-Kafka-starter` is the core dependency of the Stacksaga-Kafka Framework. it provides the essential functionalities and specifications to create and manage sagas using Kafka as the messaging backbone and ot works as Saga Execution coordinator(SEC). the dependency can be added to your Spring Boot application (the target orchestrator service) as follows,

IMPORTANT: It has been built internally using reactive programming principles, ensuring high scalability and performance.
Even though the framework operates reactively under the hood, it fully supports both reactive and non-reactive (imperative) application models.

[source,xml]
----
<dependency>
    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-kafka-starter</artifactId>
    <version>${latest-version}</version>
</dependency>
----

NOTE: Make sure to add the one of `database-support` modules as well to enable event sourcing capabilities. because `stacksaga-Kafka-starter` only provides the core saga orchestration functionalities. the event sourcing capabilities are handled by the `stacksaga-database-support` module. you can find more details about the `database-support` modules in xref:stacksaga-database-support:overview/database-support-overview.adoc[here].

IMPORTANT: `stacksaga-Kafka-starter` comes with the `stacksaga-kafka-client` dependency transitively. so you don't have to add the `stacksaga-kafka-client` dependency separately to your target services.

== What `stacksaga-Kafka-starter` does?

In high-level, +
After adding the `stacksaga-kafka-starter` dependency to your Spring Boot application, it automatically configures the necessary beans and components required for saga orchestration using Kafka. and you can provide configure your saga workflows accordingly the stacksaga-kafka specifications. once the transaction is initiated, the starter module(SEC) takes care of managing the saga's lifecycle, coordinating between different microservices, and ensuring that all steps are executed in the correct order. it also handles failures by triggering compensating actions as configured. while each execution it manages the state of the transaction and persists events to the configured event store for future-retrying, and traceability.

Let's see in step by step how the `stacksaga-kafka-starter` module works internally to manage and execute saga workflows.

NOTE: The following diagram contains all the in addition to the `stacksaga-kafka-starter` module components due to show the complete flow of a saga transaction. but here we will mainly focus on the `stacksaga-kafka-starter` module functionalities.

image::stacksaga-engines:stacksaga-kafka/stacksaga-kafka-engine-stacksaga-Kafka-starter-components-overview.svg[Stacksaga-Kafka-starter components Overview,width=800]

. As per the above diagram, as the first step, you have to xref:stacksaga-engines:stacksaga-kafka/aggregator/aggregator.adoc[create an aggregator] class. it helps to maintain the state of the saga transaction each time the saga progresses through its steps. it works as the payload of primary executions. that means the aggregator objects is serialized and sent as the message to the target service via Kafka by the framework.
. Next, you habe to create an enum for storing the saga steps and the topics of the respective events that should be triggered.
. Next, you can configure how your flow should be executed based on the aggregator state by implementing the xref:stacksaga-engines:stacksaga-kafka/saga-step-manager/saga-event-navigator.adoc[Saga Event Navigator] interface.
. Now you can trigger the SEC by using the xref:stacksaga-engines:stacksaga-kafka/saga-kafka-template/saga-kafka-template.adoc[SagaKafkaTemplate] or xref:stacksaga-engines:stacksaga-kafka/saga-kafka-template/saga-reactive-kafka-template.adoc[ReactiveSagaKafkaTemplate] class. it provides methods to start a new saga transaction and also to send events to the SEC for progressing the saga.
. Once the transaction is initiated, the SEC takes over and manages the saga's lifecycle. it coordinates between different microservices by sending messages to the appropriate Kafka topics based on the configured saga steps one by one. in case of a failure, it triggers the compensating actions in the reverse order of execution.
. Throughout the process, the SEC maintains the state of the transaction and persists events to the configured event store for future-retrying and traceability.

== Related Topics

The following topics are discussed in-detailed regarding the functionalities and specifications provided by the `stacksaga-kafka-starter` module.

* *SEC (Saga Execution Coordinator)* Related Topics +
accessing The starter module includes the implementation of the Saga Execution Coordinator (SEC) engine, which is responsible for orchestrating the saga's lifecycle, managing state transitions, and coordinating between different microservices involved in the saga based on your configurations. +
xref:stacksaga-engines:stacksaga-kafka/saga-kafka-template/saga-kafka-template.adoc[] and xref:stacksaga-engines:stacksaga-kafka/saga-kafka-template/saga-reactive-kafka-template.adoc[] can be used for accessing SEC functionalities.
* *Specifications* Related Topics +
The starter module includes specifications for defining saga steps, compensation actions, and event handling mechanisms.
These specifications provide a structured way to implement sagas in your application.
** xref:stacksaga-engines:stacksaga-kafka/aggregator/aggregator.adoc[Aggregator specifications]
** xref:stacksaga-engines:stacksaga-kafka/aggregator/aggregator_key_gen_custom_implementation.adoc[Aggregator Serialization related specifications]
** xref:stacksaga-engines:stacksaga-kafka/aggregator/aggregator_mapper_implementation.adoc[Aggregator Key Generation and Mapper related specifications]
** xref:stacksaga-engines:stacksaga-kafka/aggregator/aggregator_versioning_and_casting.adoc[Aggregator Versioning and Casting related specifications]
** xref:stacksaga-engines:stacksaga-kafka/saga-topic/saga-topic.adoc[SagaTopic specifications]
** xref:stacksaga-engines:stacksaga-kafka/saga-step-manager/saga-event-navigator.adoc[Saga Step Manager related specifications]
* Configuration Properties


