= StackSaga Admin Dashboard.

*StackSaga Admin* is the monitoring dashboard of the StackSaga framework.
It consists of UI dashboard as well as the backend server.

== StackSaga Admin Features

In brief,The Stacksaga Admin's features are as follows.

* Transaction and Tracing GUI.
* Role-based access control (RBAC) for each service.
* Maintaining instance data.
* Maintaining Aggregator and executor's metadata. etc..

=== StackSaga Admin involvement in the StackSaga ecosystem.

To have a better understanding, let's have look how the involvement of `StackSaga Admin` in the ecosystem.

image:stack-saga-high-level-diagram.svg[alt="StackSaga Admin involvement in the StackSaga ecosystem"]

StackSaga-Admin is a partial stateless application.
Because, even though you can see the transaction tracing and other data in the dashboard, that data is not saved in the admin's database.
The data coming from the Individual event-stores.

You know that in StackSaga, StackSaga-framework uses an event-store for storing the transaction data.
As per xref://[this article], it can be a single event-store or most probably, it can be multiple event-stores for each orchestrator service.
The transaction's data is saved on those event-stores separately.

Let's see how the StackSaga-Admin fetches the transaction data from the Individual event-stores.

When you add the StackSaga-framework in your utility services, it has inbuilt endpoints for expose the data to the outside world.
[ See the xref://[endpoints here]. ]

image:how-stacksaa-admin-fetch-transaction-data.svg[alt="how stacksaa admin fetch transaction data"]
