[[stacksaga_admin_jar]]
=== StackSaga Admin Jar

You can download Stacksaga Admin server executable jar in two types.

* StackSaga Admin server jar with an embedded database.
(For development)
+
*Minimum Requirements*

** Java 17 or upper
+
Download here. [ xref://[icon:download[1x]] ]

* StackSaga Admin server jar without an embedded database.
(For production)
+
*Minimum Requirements*

** Java java 17 or upper
** Selected Database.
+
NOTE: Currently, StackSaga Admin supports Mysql Database only.
+
Download here. [ xref://[icon:download[1x]] ]


After unzipping the file, you will see the jar file.
To run the jar file, run the `+START.sh+` file or the following code below.
Before run the jar, make sure to config your custom configuration in the `+application-proud.properties+` file.

* Run on the console*

[source,shell]
----
$ java -jar stack-saga-admin-1.0-SNAPSHOT.jar --spring.config.location=file:application-proud.properties
----
====
TIP: If you have installed multiple java versions on your computer, you can directly mention the java and run the executable jar like below.

[source,shellscript]
----
"C:\Program Files\Java\jdk-17\bin\java.exe" -jar stacksaga-admin-1.0-SNAPSHOT.jar
----
====

=== Update custom configurations

You can update your custom configurations for running the application.
To override the configuration properties, you can update your configurations in the `application.properties` file like below.

[source,properties]
.application.properties
----
stacksaga.admin.security.expiration-time=60000
stacksaga.admin.security.secret=wksfgfasdfgwhjrfgkrhfsfashwewnfbcfj$244#
server.port=4444
spring.liquibase.drop-first=false
spring.datasource.url=jdbc:mysql://localhost:3306/stacksaga_admin_db
spring.datasource.username=root
spring.datasource.password=mafei
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
----

TIP: If you want to add more configurations regarding the database and many more, please follow the spring reference documentation.
Because all other configurations will be applied according to the spring boot framework.