==== StackSaga Admin Jar [[stacksaga_admin_jar]]

icon:download[2x]
Here is the standalone version of StackSaga admin server.
You can download the *stack-saga-admin-server.zip*.

*Downloads*

* https://mega.nz/folder/w8lRXYyI#q5CFtVrNTCJtqYUuDzPPkA[StackSaga Admin Server - MySQL]

*Minimum Requirements*

* Java java 8 or upper
* Selected Database

After unzipping the file, you will see the jar file.
To run the jar file, run the `+START.sh+` file or the following code below.
Before run the jar, make sure to config your custom configuration in the `+application-proud.properties+` file.

*> Run on the console*

[source,shell]
----
java -jar stack-saga-admin-1.0-SNAPSHOT.jar --spring.config.location=file:application-proud.properties
----

NOTE: As you know in Spring application the default configuration file is `application.properties`.
But your custom configurations should be in the `application-proud.properties` file.
Because all the necessary configurations have been set in the default configuration file.

All the required configurations are as follows:

[source,properties]
----
#security
stacksaga.admin.security.expiration-time=60000
stacksaga.admin.security.secret=********************************
#r2dbc
spring.r2dbc.url=r2dbc:mysql://localhost:3306
spring.r2dbc.username=username
spring.r2dbc.password=*********
#liquibase
spring.liquibase.url=jdbc:mysql://localhost:3306/${stacksaga.admin.database-name}?createDatabaseIfNotExist=true}
spring.liquibase.user=${spring.r2dbc.username}
spring.liquibase.password=${spring.r2dbc.password}
#logging
logging.level.root=info
----

NOTE: For managing Database versions, https://www.liquibase.org[`liquibase`] has been used for StackSaga Admin server.
And also for accessing the database in reactive mode,
https://spring.io/projects/spring-data-r2dbc[`R2DBC`] has been used.
Due to reactive has no any framework for managing database versions, StackSaga team has used both dependencies together.
That's two database configurations should be configured here for the same database.

TIP: If you want to add more configurations regarding the database and many more, please follow the spring reference documentation.
Because all other configurations will be applied according to the spring boot framework.