[[stacksaga_admin_jar]]
=== StackSaga Admin Jar

You can download Stacksaga Admin server executable jar in two types.

* StackSaga Admin server jar with an embedded database.
(For development)
+
*Minimum Requirements*

** Java 17 or upper
+
Download here. [ xref://[icon:download[1x]] ]

* StackSaga Admin server jar without an embedded database.
(For production)
+
*Minimum Requirements*

** Java java 17 or upper
** Selected Database.
+
NOTE: Currently, StackSaga Admin supports Mysql Database only.
+
Download here. [ xref://[icon:download[1x]] ]


After unzipping the file, you will see the jar file.
To run the jar file, run the `+START.sh+` file or the following code below.
Before run the jar, make sure to config your custom configuration in the `+application-proud.properties+` file.

* Run on the console*

[source,shell]
----
$ java -jar stack-saga-admin-1.0-SNAPSHOT.jar --spring.config.location=file:application-proud.properties
----
====
TIP: If you have installed multiple java versions on your computer, you can directly mention the java and run the executable jar like below.

[source,shellscript]
----
"C:\Program Files\Java\jdk-176\bin\java.exe" -jar stacksaga-admin-1.0-SNAPSHOT.jar --spring.config.location=application.properties.
----
====


NOTE: As you know in Spring application the default configuration file is `application.properties`.
But your custom configurations should be in the `application-proud.properties` file.
Because all the necessary configurations have been set in the default configuration file.

All the required configurations are as follows:

[source,properties]
----
stacksaga.admin.security.expiration-time=60000
stacksaga.admin.security.secret=wksfgfasdfgwhjrfgkrhfsfashwewnfbcfj$244#
server.port=4444
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.drop-first=false
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=*
spring.datasource.url=jdbc:mysql://localhost:3306/stacksaga_admin_db
spring.datasource.username=root
spring.datasource.password=mafei
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.configuration.default-statement-timeout=30
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
logging.level.root=error
----

NOTE: For managing Database versions, https://www.liquibase.org[`liquibase`] has been used for StackSaga Admin server.
And also for accessing the database in reactive mode,
https://spring.io/projects/spring-data-r2dbc[`R2DBC`] has been used.
Due to reactive has no any framework for managing database versions, StackSaga team has used both dependencies together.
That's two database configurations should be configured here for the same database.

TIP: If you want to add more configurations regarding the database and many more, please follow the spring reference documentation.
Because all other configurations will be applied according to the spring boot framework.