== Sub Executors

There is a special type of executor called sub executor in Stacksaga other than the query executor and command executor.
It's used for executing the extra compensating atomic transactions in addition to the main compensating transactions.

You already know that you can only execute one atomic transaction inside the executor.
The rule is applied for both primary execution and compensating execution.
Sometimes You might want to execute another extra execution when one of compensating executions is executed.

For instance, just imagine that the system has a requirement that should be updated to another service when that the order is cancelled execution.
Then, as per the executor's rule, you cannot implement both executions in the doRevert method for canceling the order and notifying that into another server.
Because those are totally two atomic operations.
In this kind of situation, you can use a sub executor to overcome the challenge.
Based on the position that the sub execution should be executed, the sub executors are divided into two types.

1. sub-before-executors
- If the sub executor should be run before making the main compensating transaction, it can be used sub before Executors.
As per the requirement, it can be added any number of sub-before-executors into a command executor.
You can navigate the SEC to each of them one by one.
See the code implementation.
2. sub-after-executors
- If the sub executor should be run after making the main compensating transaction, it can be used a sub after Executor.
As per the requirement, it can be added any number of sub-after-executors into a command executor.
You can navigate the SEC to each of them one by one.
See the code implementation.

If it's needed to have both sub-before-executors and also sub after Executors, it is possible to do.
If it has been configured both before and after executors, the order of the entire compensating transaction is like below.

At 1st all sub before Executors will be executed that you configured into the command executor and after completing the sub before Executors, next it is executed the default compensating execution (main compensating) of the command executor.
After completing the main compensating, next it's executed the sub after Executors that you have configured into the command executor.
The diagram shows the order and relationship between the sub-before-executor, and main-revert-execution and sub-after-executor.

image:executor/Architecture-Stacksaga-command-executor-with-revert-executors.drawio.svg[alt=" Stacksaga Executors",width=100%,opts=interactive,scaledwidth=100%]
