= Transaction Event Listener

[[event_listener_for_stage_change_events]]
== Transaction State Change Listeners

After handing over the transaction to the StackSaga engine by calling the `execute` or `executeAsync` method of the `StackSagaTemplate`, the transaction is being executed and updated the status time to time after each execution (primary and compensation) in the transaction flow.
so if you want to keep listening to the transaction status changes and perform any action based on that, framework provides the way to do that.

It also can be implemented based on the environment.

. `TransactionEventListener` for non-reactive environment.
. `ReactiveTransactionEventListener` for reactive environment.

If you want to get notified about the transaction status changes, there are two ways are available in the framework.

. Using `StackSagaTemplate.getCurrentState`
. Using `TransactionEventListener` or `ReactiveTransactionEventListener`.

IMPORTANT: using `StackSagaTemplate.getCurrentState` method to get the current state of the transaction by providing the transactionId approach is not efficient because when you call this method, the engine fetches the current state of the transaction from the event-store.
but if you are using the listeners, you will be notified about the transaction status changes after each execution in the transaction flow without the need to call any method to get the current state of the transaction because the current state of the transaction is being passed to the callback method of those listeners realtime.
due to it is happening realtime you don't want to pool the transaction state. for instance in the place-order example, after executing you can push the notification to update the user about the order status changes by using those listeners.
but in some cases you might want to get the current state of the transaction even after the transaction is completed. for instance after use might need to see the details after placing order. then you can use the `StackSagaTemplate.getCurrentState` method to get the current state of the transaction by providing the transactionId.
The use cases are different for both approaches, so you can choose the one that is suitable for your use case.

IMPORTANT: While you are using the `onChange` method of the listeners, be aware that the method is invoked after each execution in the transaction flow, so make sure to perform only the required action in that method and avoid doing any heavy processing in that method because it can be caused to delay the entire transaction flow.
if you want to do some heavy processing based on the transaction status changes, it is recommended make a deep copy of the `TransactionState` object and then perform the heavy processing with a separate thread by letting the saga thread to continue the execution without being unnecessarily delayed. or you can use the `StackSagaTemplate.getCurrentState` method to get the current state of the transaction and then perform the heavy processing based on that.

=== TransactionEventListener

You can implement the `TransactionEventListener` interface to listen to the transaction events in a non-reactive environment as below.

[source,java]
----
@Slf4j
@Component
@RequiredArgsConstructor
public class PlaceOrderHandler implements TransactionEventListener<OrderDomainEntity> {
    @Override
    public void onStateChanged(TransactionState<OrderDomainEntity> state) {
        TransactionCompleteStatus currentStatus = state.getCurrentStatus();
        log.info("Current status of transaction: {}", currentStatus);
        NavigableMap<Integer, SagaExecutionEvent> executionHistory = state.getExecutionHistory();
        log.info("Execution history of transaction: {}", executionHistory);
        OrderDomainEntity currentDomainEntity = state.getCurrentDomainEntity();
        log.info("Current domain entity state: {}", currentDomainEntity);
        ZonedDateTime startedDateTime = state.getStartedDateTime();
        log.info("Transaction started at: {}", startedDateTime.toLocalDateTime());
    }
}
----

=== ReactiveTransactionEventListener

You can implement the `ReactiveTransactionEventListener` interface to listen to the transaction events in reactive environment as below.

[source,java]
----
@Slf4j
@Component
@RequiredArgsConstructor
public class ReactivePlaceOrderHandler implements ReactiveTransactionEventListener<OrderDomainEntity> {
    @Override
    public Mono<Void> onStateChanged(TransactionState<OrderDomainEntity> transactionState) {
        return Mono
                .just(transactionState)
                .doOnNext(state -> {
                    TransactionCompleteStatus currentStatus = state.getCurrentStatus();
                    log.info("Current status of transaction: {}", currentStatus);
                    NavigableMap<Integer, SagaExecutionEvent> executionHistory = state.getExecutionHistory();
                    log.info("Execution history of transaction: {}", executionHistory);
                    OrderDomainEntity currentDomainEntity = state.getCurrentDomainEntity();
                    log.info("Current domain entity state: {}", currentDomainEntity);
                    ZonedDateTime startedDateTime = state.getStartedDateTime();
                    log.info("Transaction started at: {}", startedDateTime.toLocalDateTime());
                })
                .flatMap(orderDomainEntityTransactionState -> {
                    //simulate some async processing here.
                    return Mono.delay(Duration.ofSeconds(1))
                            .then();
                });
    }
}
----

== Recommended Handler Pattern

StackSaga team suggests to implement the saga transaction related things in a separate class called `Handler` that is responsible for starting, listening and checking the status of the saga transactions.
The below code snippet is showing the recommended architecture for the Handler.

[source,java]
----
@Slf4j
@Component
@RequiredArgsConstructor
public class PlaceOrderHandler implements TransactionEventListener<OrderDomainEntity> {

    private StackSagaTemplate<OrderDomainEntity, PlaceOrderTopic> stackSagaTemplate;

    public String handle(String username, double amount, List<String> items) { //<1>
        return this
                .stackSagaTemplate
                .init(() -> {
                  //....
                })
                .....
    }

    public CustomOrderStatusView getCurrentState(String orderId) { //<2>
        return this
                .stackSagaTemplate
                .getCurrentState(orderId)
                ......

    }
    @Override
    public void onStateChanged(TransactionState<OrderDomainEntity> transactionState) { //<3>
        //....
    }
}
----

<1> The `handle` method is responsible for starting the saga transaction by using the `StackSagaTemplate` and providing the required parameters to start the transaction.
<2> Fetch the current state of the transaction by using the `StackSagaTemplate`
<3> Implement the `onStateChanged` method to listen to the transaction status changes by implementing the `TransactionEventListener` interface and override the `onStateChanged` method.