= StackSagaTemplate and Event-Listener

[[stacksaga-template-usage]]
== StackSagaTemplate

`StackSagaTemplate` is the main entry point for accessing the StackSaga engine's (SEC) functionalities in the orchestrator service.
It provides the API to start new transactions, checking the status of existing transactions.

`StackSagaTemplate` can be used in both reactive(non-blocking) and non-reactive(blocking) programming models. if you are in non-reactive environment, it can be used as below.

[[stackSagaTemplate_usage_in_non_reactive_environment]]
=== StackSagaTemplate in a Non-Reactive Environment

This demonstrates how to use the `StackSagaTemplate` to start a new saga transaction for placing an order and also how to check the current state of the transaction.

[source,java]
----
@Slf4j
@Component
@RequiredArgsConstructor
public class PlaceOrderHandler {

    private final SagaTemplate<OrderDomainEntity> stacksagaTemplate;//<1>

    public String handle(String username, double amount, List<String> items) {
        String transactionId = this.stackSagaTemplate
                //<2>
                .init(() -> {
                    OrderDomainEntity orderDomainEntity = new OrderDomainEntity();
                    {//initializing the domain entity with the required properties for the saga execution.
                        orderDomainEntity.setUsername(username);
                        orderDomainEntity.setTotalAmount(amount);
                        //...
                    }
                    return orderDomainEntity;
                })
                //<3>
                .peek(orderDomainEntity -> {
                    log.info("transactionId {}:", orderDomainEntity.getTransactionId());
                })
                //<4>
                .startWith(ValidateUserExecutor.class)
                //<5>
                .fireAndForget()
                //<6>
                .execute();
        log.info("Started place order saga with transactionId: {}", transactionId);
        return transactionId;
    }

    public void printCurrentState(String transactionId) {
        TransactionState<OrderDomainEntity> state = this
                .stackSagaTemplate
                //<7>
                .getCurrentState(transactionId)
                .execute();

        TransactionCompleteStatus currentStatus = state.getCurrentStatus(); //<8>
        log.info("Current status of transaction {}: {}", transactionId, currentStatus);
        NavigableMap<Integer, SagaExecutionEvent> executionHistory = state.getExecutionHistory();//<9>
        log.info("Execution history of transaction {}: {}", transactionId, executionHistory);
        OrderDomainEntity currentDomainEntity = state.getCurrentDomainEntity(); //<10>
        log.info("Current domain entity state: {}", currentDomainEntity); //<11>
        ZonedDateTime startedDateTime = state.getStartedDateTime(); //<12>
        log.info("Transaction {} started at: {}", transactionId, startedDateTime.toLocalDateTime());
    }
}
----

<1> Autowire the `StackSagaTemplate` in your class. you have to provide the custom xref:stacksaga-sync/orchestrator/domain-entity.adoc#creating_custom_domain_entity[`DomainEntity`] as the generic parameter of the `StackSagaTemplate`.
<2> Use the `init` operator to initialize the transaction by providing a supplier of the custom DomainEntity. this method is used to create the initial state of the transaction by providing the required properties for the saga execution in the DomainEntity.
<3> Use the `peek` operator (optional) to perform any action with the initialized DomainEntity before starting the execution. the usage of this operator is that is to see the generated transactionId after initializing the DomainEntity because #the transactionId is generated and set in the DomainEntity by the framework at the time of passing via `init` operator#. therefore, you can use this operator to see the generated transactionId before starting the execution.
<4> Use the `startWith` operator to specify the first xref:stacksaga-sync/orchestrator/executor_architecture.adoc[executor] that should be triggered to start the transaction.

<5> Use the `fireAndForget` operator to start the execution of the transaction as fire-and-forget mode. that means the transaction totally runs in the background, and you don't have to wait for the execution to complete. it runs using the request thread only for initializing the transaction. after initializing the transaction, the request thread is released to serve other requests. the execution of the transaction runs in the background using a separate thread pool that is managed by the framework.

<6> Use the `execute` operator to start the execution of the transaction in blocking way.

<7> Use the `getCurrentState` operator to get the current state of the transaction by providing the transactionId. this method is used to retrieve the current state of the transaction at any point in time by providing the transactionId. yu can see all the details about the transaction state in the returned `TransactionState` object such as the current status of the transaction, the execution history, the current state of the domain entity, the started time and many more details.
<8> Get the current status of the transaction from the `TransactionState` object.
<9> Get the execution history of the transaction from the `TransactionState` object. the execution history is a navigable map that contains all the executed endpoints in the transaction flow (primary and compensation) with their metadata such as the execution status, completed time event name and more.
<10> Get the current state of the domain entity from the `TransactionState` object. this is the latest state of the domain entity after applying all the changes that are done by the executed endpoints in the transaction flow.
<11> Log the current state of the domain entity.
<12> Get the started time of the transaction from the `TransactionState` object and log it.

NOTE: There is another way to being updated about the transaction status changes by using the xref:#event_listener_for_stage_change_events[EventListener].

IMPORTANT: Go through the Javadoc of the `TransactionState` class to see all the features that are provided in the transaction state object to get more insights about the transaction.

=== StackSagaTemplate in a Reactive Environment

If you are in a reactive environment, you can use the `StackSagaTemplate` in a non-blocking way by using the reactive operators provided by the template as below.

[source,java]
----
@Slf4j
@Component
@RequiredArgsConstructor
public class PlaceOrderHandler {

    private final SagaTemplate<OrderDomainEntity> stacksagaTemplate;

    public Mono<String> handle(String username, double amount, List<String> items) {
        return this.stackSagaTemplate
                .init(() -> {
                    OrderDomainEntity orderDomainEntity = new OrderDomainEntity();
                    {//initializing the domain entity with the required properties for the saga execution.
                        orderDomainEntity.setUsername(username);
                        orderDomainEntity.setTotalAmount(amount);
                        //...
                    }
                    return orderDomainEntity;
                })
                .peek(orderDomainEntity -> {
                    log.info("transactionId {}:", orderDomainEntity.getTransactionId());
                })
                .startWith(ValidateUserExecutor.class)
                .fireAndForget()
                //<1>
                .executeAsync()
                .map(transactionId -> "Order placed successfully with transaction id: " + transactionId);
    }

    public void printCurrentState(String transactionId) {
        TransactionState<OrderDomainEntity> state = this
                .stackSagaTemplate
                .getCurrentState(transactionId)
                .execute();

        TransactionCompleteStatus currentStatus = state.getCurrentStatus();
        log.info("Current status of transaction {}: {}", transactionId, currentStatus);
        NavigableMap<Integer, SagaExecutionEvent> executionHistory = state.getExecutionHistory();
        log.info("Execution history of transaction {}: {}", transactionId, executionHistory);
        OrderDomainEntity currentDomainEntity = state.getCurrentDomainEntity();
        log.info("Current domain entity state: {}", currentDomainEntity);
        ZonedDateTime startedDateTime = state.getStartedDateTime();
        log.info("Transaction {} started at: {}", transactionId, startedDateTime.toLocalDateTime());
    }
}
----

<1> The main highlight of the reactive programming model is that it allows you to execute the transaction in a non-blocking way by using the `executeAsync` operator. this operator returns a `Mono<String>` that contains the transactionId of the started transaction. you can use this transactionId to check the current state of the transaction at any point in time by using the `getCurrentState` operator as shown in the above example.

In reactive mode there is another important operator called `fireAndWatch` that allows you to start the transaction in a fire-and-watch mode. this operator returns a `Flux<SagaExecutionEvent>` that emits the execution events of the transaction as they occur. you can use this operator to watch the execution of the transaction in real-time and perform any action based on the emitted events. in case of transient failures, the pipeline is ended and the listing of the events haled via the xref:#event_listener_for_stage_change_events[EventListener] furthermore.

[[event_listener_for_stage_change_events]]
== Transaction State Change Listeners

After handing over the transaction to the StackSaga engine by calling the `execute` or `executeAsync` method of the `StackSagaTemplate`, the transaction is being executed and updated the status time to time after each execution (primary and compensation) in the transaction flow.
so if you want to keep listening to the transaction status changes and perform any action based on that, framework provides the way to do that.

It also can be implemented based on the environment.

. `TransactionEventListener` for non-reactive environment.
. `ReactiveTransactionEventListener` for reactive environment.

If you want to get notified about the transaction status changes, there are two ways are available in the framework.

. Using `StackSagaTemplate.getCurrentState`
. Using `TransactionEventListener` or `ReactiveTransactionEventListener`.

IMPORTANT: using `StackSagaTemplate.getCurrentState` method to get the current state of the transaction by providing the transactionId approach is not efficient because when you call this method, the engine fetches the current state of the transaction from the event-store.
but if you are using the listeners, you will be notified about the transaction status changes after each execution in the transaction flow without the need to call any method to get the current state of the transaction because the current state of the transaction is being passed to the callback method of those listeners realtime.
due to it is happening realtime you don't want to pool the transaction state. for instance in the place-order example, after executing you can push the notification to update the user about the order status changes by using those listeners.
but in some cases you might want to get the current state of the transaction even after the transaction is completed. for instance after use might need to see the details after placing order. then you can use the `StackSagaTemplate.getCurrentState` method to get the current state of the transaction by providing the transactionId.
The use cases are different for both approaches, so you can choose the one that is suitable for your use case.

IMPORTANT: While you are using the `onChange` method of the listeners, be aware that the method is invoked after each execution in the transaction flow, so make sure to perform only the required action in that method and avoid doing any heavy processing in that method because it can be caused to delay the entire transaction flow.
if you want to do some heavy processing based on the transaction status changes, it is recommended make a deep copy of the `TransactionState` object and then perform the heavy processing with a separate thread by letting the saga thread to continue the execution without being unnecessarily delayed. or you can use the `StackSagaTemplate.getCurrentState` method to get the current state of the transaction and then perform the heavy processing based on that.

=== TransactionEventListener

You can implement the `TransactionEventListener` interface to listen to the transaction events in a non-reactive environment as below.

[source,java]
----
@Slf4j
@Component
@RequiredArgsConstructor
public class PlaceOrderHandler implements TransactionEventListener<OrderDomainEntity> {
    @Override
    public void onStateChanged(TransactionState<OrderDomainEntity> state) {
        TransactionCompleteStatus currentStatus = state.getCurrentStatus();
        log.info("Current status of transaction: {}", currentStatus);
        NavigableMap<Integer, SagaExecutionEvent> executionHistory = state.getExecutionHistory();
        log.info("Execution history of transaction: {}", executionHistory);
        OrderDomainEntity currentDomainEntity = state.getCurrentDomainEntity();
        log.info("Current domain entity state: {}", currentDomainEntity);
        ZonedDateTime startedDateTime = state.getStartedDateTime();
        log.info("Transaction started at: {}", startedDateTime.toLocalDateTime());
    }
}
----

=== ReactiveTransactionEventListener

You can implement the `ReactiveTransactionEventListener` interface to listen to the transaction events in reactive environment as below.

[source,java]
----
@Slf4j
@Component
@RequiredArgsConstructor
public class ReactivePlaceOrderHandler implements ReactiveTransactionEventListener<OrderDomainEntity> {
    @Override
    public Mono<Void> onStateChanged(TransactionState<OrderDomainEntity> transactionState) {
        return Mono
                .just(transactionState)
                .doOnNext(state -> {
                    TransactionCompleteStatus currentStatus = state.getCurrentStatus();
                    log.info("Current status of transaction: {}", currentStatus);
                    NavigableMap<Integer, SagaExecutionEvent> executionHistory = state.getExecutionHistory();
                    log.info("Execution history of transaction: {}", executionHistory);
                    OrderDomainEntity currentDomainEntity = state.getCurrentDomainEntity();
                    log.info("Current domain entity state: {}", currentDomainEntity);
                    ZonedDateTime startedDateTime = state.getStartedDateTime();
                    log.info("Transaction started at: {}", startedDateTime.toLocalDateTime());
                })
                .flatMap(orderDomainEntityTransactionState -> {
                    //simulate some async processing here.
                    return Mono.delay(Duration.ofSeconds(1))
                            .then();
                });
    }
}
----


[[recommended-handler-pattern]]
== Recommended Handler Pattern

StackSaga team suggests to implement the saga transaction related things in a separate class called `Handler` that is responsible for starting, listening and checking the status of the saga transactions.
The below code snippet is showing the recommended architecture for the Handler.

[source,java]
----
@Slf4j
@Component
@RequiredArgsConstructor
public class PlaceOrderHandler implements TransactionEventListener<OrderDomainEntity> {

    private StackSagaTemplate<OrderDomainEntity> stackSagaTemplate;

    public String handle(String username, double amount, List<String> items) { //<1>
        return this
                .stackSagaTemplate
                .init(() -> {
                  //....
                })
                .....
    }

    public CustomOrderStatusView getCurrentState(String orderId) { //<2>
        return this
                .stackSagaTemplate
                .getCurrentState(orderId)
                ......

    }
    @Override
    public void onStateChanged(TransactionState<OrderDomainEntity> transactionState) { //<3>
        //....
    }
}
----

<1> The `handle` method is responsible for starting the saga transaction by using the `StackSagaTemplate` and providing the required parameters to start the transaction.
<2> Fetch the current state of the transaction by using the `StackSagaTemplate`
<3> Implement the `onStateChanged` method to listen to the transaction status changes by implementing the `TransactionEventListener` interface and override the `onStateChanged` method.

