====  Creating the aggregator

You know that the request comes to the order-service first (for downstream services), and it tries to handle the entire request by calling other utility services one by one in a sequence order.
To start the execute the request, the `order-service` should have an xref:architecture:aggregator.adoc[Aggregator] class that extend from the `SagaAggregator` class.
The custom aggregator class contains all the data which is used for all the atomic transactions of the LRT.
Simultaneously, it is required an implement of `SagaSerializable` for the specific aggregator.

[source,java]
----
package org.example.aggregator;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import org.example.aggregator.dto.OrderItem;
import org.stacksaga.Aggregator;
import org.stacksaga.SagaSerializable;
import org.stacksaga.core.annotation.SagaAggregator;
import org.stacksaga.core.annotation.SagaAggregatorVersion;

import java.util.List;

//<1>
@SagaAggregator(
        version = @SagaAggregatorVersion(major = 1, minor = 0, patch = 0),
        name = "PlaceOrderAggregator",
        sagaSerializable = PlaceOrderAggregatorSerializer.class
)
@Getter
@Setter
@ToString
public class PlaceOrderAggregator extends Aggregator { //<2>


    /**
     * The relevant user to the order.
     */
    @JsonProperty("user_id")
    private String userId;
    /**
     * The item list that user order.
     */
    @JsonProperty("items")
    private List<OrderItem> items;

    /**
     * The amount to be paid.
     */
    @JsonProperty("amount")
    private Double amount;

    /**
     * Pre-Auth Reference for release or make the payment.
     */
    @JsonProperty("pre_auth_ref")
    private String preAuthRef;

    /**
     * Payment ID after the payment.
     */
    @JsonProperty("payment_id")
    private String paymentId;

    @JsonProperty("executions")
    private List<String> executions = new ArrayList<>();

    @JsonIgnore
    private Boolean hasRevertError = false;

    //<3>
    public PlaceOrderAggregator() {
        super(PlaceOrderAggregator.class);
    }
}

//<4>
class PlaceOrderAggregatorSerializer extends SagaSerializable<PlaceOrderAggregator> {

    public PlaceOrderAggregatorSerializer() {
        //<5>
        PlaceOrderAggregator placeOrderAggregator = new PlaceOrderAggregator();
        placeOrderAggregator.setUserId("user-1");
        placeOrderAggregator.setAmount(100.00);
        placeOrderAggregator.setItems(new ArrayList<>());
        placeOrderAggregator.getItems()
                .add(OrderItem.builder()
                        .itemId("item-1")
                        .itemPrice(100.00)
                        .build()
                );
        this.put("sample-1", placeOrderAggregator);
    }
}
----

TIP: To make the code more readable and clear, https://projectlombok.org/:[`lombok`] has been used there.
It is not required to use lombok at all, you are free to use the traditional way by creating getters and setters manual.

<1> The custom PlaceOrderAggregator class has been annotated with the `@SagaAggregator` annotation.
+
version:: The version of the aggregator.
This version will be updated if you make some changes in the feature by changing the executors (adding or removing).
See xref:architecture:aggregator_versioning.adoc[more details]
+
name:: The unique name of the aggregator. this aggregator should be a static one. it cannot be changed. if it is changed, the aggregator is considered as another new one.
+
sagaSerializable:: To verify whether the aggregator object is serializable, it is recommended to provide a xref:framework:aggregator_serialization.adoc[SagaSerializable] implementation for the relevant aggregator.
This ensures that the aggregator can be correctly serialized and deserialized during application startup.
The primary advantage of providing a SagaSerializer is that any serialization or deserialization issues will be detected at startup, rather than during transaction processing, thereby preventing runtime failures.
If you do not provide the `SagaSerializer`, the default SagaSerializer is used.
It also checks whether the aggregator is serializable or not by creating an object internally.
But if you are using more complex data structure, it is recommended to provide the `SagaSerializable` implementation for the relevant aggregator.

<2> Extends the `PlaceOrderAggregator` by the `Aggregator` class to make it an aggregator.

<3> Due to extending the `PlaceOrderAggregator` by the `Aggregator` class, you have to provide the constructor with calling the superclass constructor to pass the exact class as a parameter.

<4> The PlaceOrderAggregatorSerializer class is created to verify whether the aggregator is serializable or not.
The class should be extended from SagaSerializable by passing the aggregator class as the Type.

<5> Create the default constructor and provide the different sample aggregator objects as you wish to use. `this.put()` method is used for passing the sample aggregator objects to the framework.

In the `PlaceOrderAggregator` has the data that we want to access while the entire transaction process.
Those data will be updated time to time from each execution.

Now the aggregator is ready to store and carry out the data throughout the entire process.

