==== Order-Service Overview.

You know that we have to access more services besides this `order-service` to fully complete the entire place-order request.
To access those services in general, you would use the *service-layer* and call those services manually by using any httpclient like RestTemplate, Feign client, Okhttp, and so on.

Instead of that manual unorganized way, StackSaga offers better template for each execution.
It is called as xref:architecture:executor_architecture.adoc[executors].

According to the xref:architecture:saga-architecture.adoc[Saga design pattern], you know that we should have a Compensating process for all the atomic executions.
(All the executions that make some changes in a database).
Due to the fact that the StackSaga framework is one of Saga implementations, it should be provided the primary execution and also a Compensating execution to make a Compensating when the entire process is failed at any point.

Based on having a Compensating or not, the executors are two types called xref:architecture:command_executor_architecture.adoc[command-executor] and xref:architecture:query_executor_architecture.adoc[query-executor].
`command-executor` have both *Primary execution* and the *Compensating execution*.
If it is `query-executor`, it has only *Primary execution*.

==== How StackSaga combines with Controller Service and Repository architecture?

In spring applications we follow `controller`, `service` and `repository` layered architecture in general.

////
StackSaga suggest another middle layer between the `controller` layer and the `service` layer called `executor-layer`.
The `executor-layer` is the place the xref:architecture:executor_architecture.adoc[executors] are created.
////

Let's see step by step how StackSaga involves the process.

Here you can see the entire process in a diagram how StackSaga works in the order-service (orchestrator-service).
You can see some additional layers in the diagram due to this demo following the xref:architecture:Saga-CHES-architecture.adoc[CHES&D] layered architecture as a best practice.

image:stacksaga-example-executors-architecture-in-order-service.drawio.svg[alt="stacksaga microservice example executors architecture in order service"]

In brief, The client makes an order place request and the request comes to the *order-service* via the *API-Cloud-Gateway*.
And then initializes the aggregator object with the order details that received from the request.
After that, the aggregator is passed to the handler class called `PlaceOrderHandler`.
Inside the handler class, the aggregator object is handed over to the SEC for further processing.

Here you can see the summarized table of the execution's relations for your convenience.

[.scrollable]
--
[cols=".no-wrap, .normal, .no-wrap, .no-wrap, .no-wrap, .no-wrap"]
|===
|Executor Class Name| Execution_Requirement | Target_Service | Type | Process-Execution |  Revert-Execution

|xref://[`UserDetailExecutor`]
|Fetch the user's details
|`user-service`
|[.badge-green]*QUERY_EXECUTOR*
|`getUserDetails`
| -

|xref://[`OrderInitializeExecutor`]
|Initialize the order at the first.
|`order-service`
|[.badge-yellow]*COMMAND_EXECUTOR*
|`initializeOrder()`
|`cancelOrder()`

|xref://[`PreAuthExecutor`]
|Make the Pre-Auth process.
|`payment-service`
|[.badge-yellow]*COMMAND_EXECUTOR*
|`makePreAuth()`
|`releasePreAuth()`

|xref://[`StockUpdateExecutor`]
|Update the stock from the store.
|`stock-service`
|[.badge-yellow]*COMMAND_EXECUTOR*
|`updateStock()`
|`restoreStock()`

|xref://[`MakePaymentExecutor`]
|Finalize the order by making the real payment.
|`payment-service`
|[.badge-yellow]*COMMAND_EXECUTOR*
|`makePayment()`
| ?

|===

--