= Stacksaga Event Store

Event-store is the location that StackSaga stores the data that is relevant to the transaction execution as well as the storing the metadata of the components that you provided like *aggregator details*, *executor details*, *application version details,* etc. all the data you can see through the xref:stacksaga-admin:stacksaga-cloud-window.adoc[StackSaga Cloud-Window].
You can configure the database for the event-store as the pattern of database per service.

Otherwise, you can provide one event-store for all services.
But as the best practice, event-store per service is recommended.
You can define a separate schema for event-store by providing the configurations.

. xref:one_event_store_per_service[One Event-Store Per Service.]
. xref:single_event_store_for_all_services[One Common Event-Store For All Services.]

include::the_requirement_of_the_event_store.adoc[]



[[one_event_store_per_service]]
include::one_event_store_per_service.adoc[]


[[single_event_store_for_all_services]]
include::single_event_store_for_all_services.adoc[]


