== StackSaga in High-level

In the xref:index.adoc[], We got a clear idea of how microservice architecture works, and what are the challenges that we have to face when implementing the microservice in traditional way.

Here, we are going to see how the StackSaga works together with typical microservice architecture.
It shows how StackSaga does impact on the default https://spring.io/microservices[spring boot microservice architecture].

For your convenience, both *Spring Microservice Architecture* and **Spring Microservice Architecture With StackSaga** diagrams have been added here.

=== *Spring Microservice Architecture* [[spring_microservice_architecture]]

image:microservice-high-level-diagram.svg[StackSaga High-level architecture,700]

=== **Spring Microservice Architecture With StackSaga**

image:stack-saga-high-level-diagram.svg[alt="StackSaga High-level architecture",700]

After adding StackSaga in to the microservice ecosystem, you can see there are some additional components in the high-level architecture diagram.

TIP: In the diagram, the *Gray* color components are related to the typical microservice architecture, and newly added StackSaga related components and connectivity-lines have been colored by *Green* color for your convenience.

* You already know that the StackSaga framework provides the orchestration facility in the microservice architecture.
So With the inclusion of StackSaga one of your services, the service become an orchestrator service.
For instance, if we want to manage a sequence of transactions from the order-service, we should add StackSaga to the order-service only.
So you are able to see in the diagram we have added StackSaga into the *service-c*.
Due to adding stacksaga to the *service-c*, you can see that we have provided an extra database schema as the event-store.
Because Stacksaga requires a database for managing the event-store.

+
TIP: Even though the diagram shows event-store per service, It can be configured as a single event-store for all services if the application is currently not a large one. *Read more*.
+
TIP: It is recommended to utilize one of the StackSaga database implementations that corresponds to the primary database of the specific service.
This approach eliminates the need for configuring an additional separate database, thereby simplifying the overall architecture. +
As an example, If the order-service uses *MYSQL* database as the *primary database*, you can use the `stacksaga-mysql-support` implementation for the event-store.

NOTE: There is no requirement to integrate StackSaga into all services within the ecosystem.
It can be added selectively to the services that will benefit from its usage.
For services that do not involve complex business domains, there is no necessity to incorporate StackSaga.

We had a quit a simple idea over this high-level overview.
Let's dive in to the deeper step by step to have a better understanding.
