= Introduction to StackSaga

Stacksaga is a Saga Orchestration engine framework that built top of the spring boot framework.
Orchestration engine helps you to manage your work flows to execute the primary executions and also the compensating executions in a very handy way to overcome the eventual consistency according to the saga design pattern.
And also you can see here some of the major features that StackSaga provides.

* Saga Orchestration engine for managing primary and compensating work flows.
* Transaction Coordination
* Idempotency (Ensures that repeating the same operation multiple times has the same effect as performing it once, which is crucial for reliability.)
* Transactions Asynchronous-Retrying
* Event sourcing (State Management)
* Monitoring Distributed transaction tracing via the StackSaga xref:stacksaga-admin:stacksaga-cloud-window.adoc[Cloud-Window].
* Concurrency Control
* Managing the Dual consistency problem.
And many more…


== Why StackSaga?[[why_stacksaga_should_be_used]]

If you implement the Saga orchestration design pattern in your system, you have to manually manage the work flows.
It's pretty tough to handle manually, like making sure the compensating actions are in the right order and also safely storing all the events for asynchronous retrying.
To get the hang of the implementation, let's check out an example.

Just imagine an E-Commerce application, and it should place an order.
Even though this action is a single one from the clint perspective, if we are in microservices architecture, that single action consists of multiple sub operations like initialize the order, collecting user details, making pre-auth, updating stocks, making the real payment and so on.
Doing these sub operations in sequence order is quite easy at first glance.
But all the time these sub operations might not be executed smoothly.

- Sometimes an error can occur while executing the last process or after some executions are done.
Then, the compensating executions have to be executed in descending order (last-in, first-out (LIFO)).
- Sometimes an error can occur due to resources unavailable like connection issues or the target service is unavailable temporarily.
If there is this kind of situation in the Saga, it's not recommended the starting compensating process.
Because eventually, we will be able to execute the execution successfully after the resources are available.
Here you have to implement a schedule mechanism to check the resource availability.

- Even if you managed to handle all those challenges.
Sometimes you may have to face dual-consistency problems as well.

Likewise, a lot of challenges will be covered by Stacksaga.
As a developer, you only have to focus on the business case if you are using StackSaga on your system.
The Stacksaga will take care of all other saga things and many challenges.

[[stacksaga_components]]
== Stacksaga-Components

include::stacksaga-components.adoc[]

include::high_level_architecture.adoc[]