= StackSaga execution coordinator. (SEC) [[SEC]]

== Overview

Due to the reason of Stacksaga is one of Saga orchestration frameworks, a central orchestration engine is required to handle the workflow based on the programmatic navigation like invoking primary-executions, the compensation-executions and as well as retrying the transaction in case of network failures.
The engine that manages all that responsibilities is called as StackSaga execution coordinator in Stacksaga.

SEC performs the following duties.

== Duties of SEC

. Execute the primary and compensation executions of the LRT.
. Navigate the transaction work flow based on the programmatic navigation.
. Identifying the errors of the atomic executions.
. Retrying the transactions
. Scheduling the executions
. Managing dual consistency problem
. State management
. Event publishing
. Aggregator states serialization and Deserialization

To fulfill the above duties, SEC interacts with your code via the xref:aggregator.adoc[Aggregators] and the xref:executor_architecture.adoc[Executors] that provide in your system.

Let's see the fundamental involvement of SEC in the framework with an example.

Let's get the same example that E-Commerce application.
Then you know we have to create an aggregator for storing necessary data.
And also we have to create the executors for each atomic transaction.
Creating aggregator and executors is not enough to start the execution.
To run the execution, we have to notify SEC with the starting executor and the starting aggregator.
Then the SEC will execute each executor one by one based on the navigation that each executor does.
As an example, if we provide the starting executor as order-init executor, it's started from that executor, and when it's executed, that particular executor will navigate to the next executor based on the logic.
(Providing the execution flow is fully dynamic in Stacksaga.
It shouldn't be a pre-defined one)

image:stack-saga-e-store-example-SEC.drawio.svg[alt="StackSaga  StackSaga Execution Coordinator (SEC)",width=100%,opts=interactive,scaledwidth=100%]

Here you can see how the SEC does work for managing work flow and publishing events in high-level.

. You can access the orchestration engine and start the process by providing the initial aggregator data and initial executor.
. Then coordinator coordinates and manages the work flow based on the navigation that you command in the executors.
Each executor will be invoked by SEC, and then your methods will be called for communicating with target services.
. If there's a primary execution error, Handle the failure recovery by executing Compensating Requests.

NOTE: If you want to see how SEC works for each transaction mode in detail, please refer xref:architecture:stack_saga_transaction_type.adoc[StackSaga Transaction Types].
It will give you a better understanding of StackSaga framework as well.

