:description: Learn how to integrate the Stacksaga MySQL Agent for Stacksaga Kafka orchestrating and retrying distributed transactions in Spring Boot microservices. Discover configuration, thread pool management, and token range partitioning for robust MySQL-based event store processing.
:keywords: Stacksaga, MySQL Agent, Spring Boot, Distributed Transactions, Transaction Retrying, Microservices, Event Store, Thread Pool, Token Range, Orchestrator, R2DBC, Resilience, Java, Scheduler, stacksaga-agent-mysql-starter

:starter_name: stacksaga-kafka-agent-mysql-starter
:data_source: R2DBC Mysql datasource
:data_source_prefix: spring.r2dbc.*


= Stacksaga Kafka Mysql Agent

== `{starter_name}`

`{starter_name}` is one of the xref:implementations:stacksaga-kafka/stacksaga-agent/stacksaga-kafka-agent-overview.adoc[Stacksaga Kafka Agent implementations] that for supporting Mysql based Orchestrator services for retrying the transactions in Kafka based microservices.

`{starter_name}` is a *ready to use* dependency. so you can create your own spring boot project and add the `{starter_name}` as a dependency and run your application with few configurations.

IMPORTANT: `{starter_name}` internally uses runs with reactive model. so make sure to create your agent application as a WebFlux spring boot application.

.Adding `{starter_name}` as a dependency
[source,xml]
----
<dependency>
    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-kafka-agent-mysql-starter</artifactId>
    <version>${org.stacksaga.version}</version>
</dependency>
----

After adding the dependency, update the xref:#configuration-properties[configuration properties] of the application as needed.

== Transaction retrying with `{starter_name}`

NOTE: If you are totally new to stacksaga-agent, read the xref:ROOT:stacksaga-agent.adoc[Common approach of Stacksaga Agent] article first.

As mentioned xref:ROOT:stacksaga-agent.adoc[there], the agent acquires a token range for retrying from the entire transaction set from the event store.

