:description: Learn how to integrate Stacksaga with Scylladb using the reactive support module. Step-by-step guide for schema setup, connection configuration, and transaction recovery in distributed systems.
:revnumber: 1.0.0
:revdate: {localdate}
:keywords: Stacksaga, Scylladb, Reactive Support, Database Integration, Event Store, Transaction Recovery, Distributed Systems, Java, Orchestrator, Schema Creation, Connection Configuration, High Throughput, Multi-Region, Idempotency, Saga design pattern, Spring Boot, Spring WebFlux, Spring Saga

= Stacksaga Scylladb Reactive Support

== Overview

Configuring Scylladb as the event store for Stacksaga orchestrator applications is almost similar to configuring xref:cassandra-database-support/stacksaga-cassandra-support.adoc[] as the event store.
because the same dependency is used for both Scylladb and Cassandra.
if you prefer to use Scylladb driver instead of Cassandra driver, you can exclude the Cassandra driver dependency from `spring-boot-starter-data-cassandra` and include the Scylladb driver dependency in your project as below.

//

[[adding-scylladb-support]]
=== Configuring Scylladb as the Event Store

[source,xml]
----
<dependency>
    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-cassandra-reactive-support</artifactId>
    <version>${org.stacksaga.version}</version>
    <exclusions>
        <!--<exclusion>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-cassandra-api-servlet</artifactId>
        </exclusion>-->
        <exclusion>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-cassandra-api-webflux</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<!--additional-->
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-cassandra</artifactId>
    <!--exclude the com.datastax.oss:java-driver-core-->
    <exclusions>
        <exclusion>
            <groupId>com.datastax.oss</groupId>
            <artifactId>java-driver-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<!--add the com.scylladb:java-driver-core-->
<dependency>
    <groupId>com.scylladb</groupId>
    <artifactId>java-driver-core</artifactId>
    <version>4.17.0.0</version> <!-- Check for the latest version -->
</dependency>

----

Read the xref:cassandra-database-support/stacksaga-cassandra-support.adoc[Stacksaga Cassandra Support] documentation for more details.