== Revert After Executor. [[revert_after_executor]]

[source,java]
----
@SagaExecutor(executeFor = "inventory-service",value = "SampleAfterExeStockUpdate") //<1>
public class SampleAfterExeStockUpdate implements RevertAfterExecutor<PlaceOrderAggregator, StockUpdateExecutor> { //<2>

    //<3>
    @Override
    public RevertAfterStepManager<PlaceOrderAggregator, StockUpdateExecutor> doProcess(
            PlaceOrderAggregator finalAggregatorState, //<4>
            NonRetryableExecutorException processException, //<5>
            RevertHintStore revertHintStore, //<6>
            RevertAfterStepManagerUtil<PlaceOrderAggregator, StockUpdateExecutor> stepManager, //<7>
            String idempotencyKey //<8>
    ) throws RetryableExecutorException { //<9>
        try {
            //<10>
            //Access the necessary data from the finalAggregatorState,processException and processException objects and call your target service.
            //Add the data to the revertHintStore If there is any data that should be added to access by the subsequent compensation executions.
            if (condition) {
                //<11>
                return stepManager.next(NextAfterExecutor.class, () -> "UPDATED");
            } else {
                //<12>
                return stepManager.complete(() -> "UPDATED");
            }
        } catch (ResourceUnavailableException e) { //<13>
            throw RetryableExecutorException.buildWith(e).build();
        }
    }
}

----


<1> *@SagaExecutor*: annotate your *revert-before* executor class with `@org.stacksaga.annotation.SagaExecutor` annotation.
The annotation provides the spring bean capabilities and also another metadata for the StackSaga framework.
+
executeFor::
The name of the target service that the executor goes to access.

value::
The bean name of the executor.
The executor is identified with this value by StackSaga engine.
After configuring the bean name, it cannot be changed at all.
If you want to the class package, it does not matter without changing the configured name.
See more.

<2> *RevertAfterExecutor<A, E>*: Your Executor should be implemented from the `RevertAfterExecutor<A,E>`.
Generic <A>:: The aggregator class of the executor.
Generic <E>:: Which is the target xref:framework:saga_executors.adoc#command_executor[command-executor] of this *revert-after-executor*.

<3> Override the `doProcess()` method that `RevertAfterExecutor` provides.
That is the method is executed by the StackSaga engine.

<4> *finalAggregatorState*: The final aggregator state when the process exception is thrown.
It is identical to the *finalAggregatorState* that discussed in the xref:saga_executors.adoc#finalAggregatorState[command-executor's `revert()`] method.

<5> *NonRetryableExecutorException*: The exception that was thrown by the last executor.
It is identical to the *NonRetryableExecutorException* that discussed in the xref:saga_executors.adoc#NonRetryableExecutorException[command-executor's `revert()`] method.

<6> *revertHintStore:* This is the payload for using carrying the data into the subsequent compensation executions.
It is identical to the *revertHintStore* that discussed in the xref:saga_executors.adoc#revertHintStore[command-executor's `revert()`] method.

<7> *stepManager* is used to navigate the compensation executions. if there is another *revert-after-executor*, after the current *revert-after-executor* for the same *command-executor*, you can use `stepManager.next()` to navigate to the next *revert-after-executor*.
or otherwise, if there is no any revert-after executor for the same *command-executor*, you can use `stepManager.complete()` to command to the SEC that revert-after executions are done for the mentioned *command-executor*. and go ahead,

<8> *idempotencyKey:* The idempotency key for the *revert-after-executor* that assigned by the SEC.

<9> *RetryableExecutorException:*
If the `doRevert` method has a *RetryableExecutorException* (resource unavailable error,) it is allowed to throw it.
+
WARNING: any compensation execution can have only *resource-unavailable* errors as per the saga design pattern.
you have to carefully handle the execution without any error except the resource-unavailable errors.
if there is unhandled error while executing the `doRevert` method, the entire execution is terminated.
and then you have to manually handle the terminated transactions.

<10> In the method body, you can call your target-service to execute the atomic compensation-execution.
Yon can access any data from the *finalAggregatorState* , *processException* or *processException* objects.
And also if you want to put some data for accessing the subsequent compensation execution, you can use the *revertHintStore.put()* method.

<11> Based on your condition, if there is another *revert-before-executor*, you can command to the SEC to the next *revert-after-executor* by using `stepManager.next()` method.

<12> Based on your condition, if there is no more *revert-after-executors* for the mentioned *command-executor*, you can return `stepManager.complete()` method.
(See xref:architecture:executor_architecture.adoc#sub-executors[how the executors are executed] when one primary atomic execution has multiple compensation.)


<13> You can catch the resource-unavailable errors in the `doRevert` method and throw it by wrapping with a `RetryableExecutorException` to stop the execution temporarily.