= Saga Executors. [[saga_executors]]

According to the saga design pattern, sub processes (atomic executions) can have two executions called process execution and compensation execution.
And those executions you van create as the methods in your application anywhere.

. *<<query_executor,Query executors>>*: If some atomic process has no compensation, that kind of process is used in a query executor.
. *<<command_executor,Command executors>>*:
If some atomic process has a compensation (revert execution), that kind of process is used in a command executor. +
*Revert executors*: For the compensation process of the command executor it can be used other sub processes if you need.
... *<<revert_before_executor,Revert Before Executors>>*: If you want to execute an atomic process before executing the main revert process, you can create a Revert-Before-Executor.
... *<<revert_after_executor,Revert After Executors>>*: If you want to execute an atomic process after executing the main revert process, you can create a Revert-Before-Executor.

include::query_executor.adoc[]

include::command_executor.adoc[]