= Saga Executors. [[saga_executors]]

As per the StackSaga's xref:architecture:executor_architecture.adoc[Executor-Architecture], the executors are used for executing the atomic execution of the LRT by the SEC.
The executors can be divided like below based on the usage.

. *xref:architecture:query_executor_architecture.adoc[Query-Executors]*: If some atomic process has no Compensating, that kind of process is used in a query executor. query-executor class has only one method called `doProcess()` for executing the primary execution.
. *xref:architecture:query_executor_architecture.adoc[Command-Executors]*:
If some atomic execution has a compensating (revert execution), that kind of execution should be implemented in command executor.
The command-executor has two methods called `doProcess()` and `doRevert()`.
For executing the primary execution and revert execution respectively.

+
Most probably an atomic execution may have one compensation.
But in some cases, an atomic execution may have multiple compensations.
In such a case, you can add extra compensations in to your command-executor.
Based on the order of the compensations are done, the extra compensation executors are two types.
+

... *xref:revert_before_executor[Revert Before Executors]*: If the extra compensation should be executed before the main compensation, it is called Revert-Before-Executor.
... *xref:revert_after_executor[Revert After Executors]*: If the extra compensation should be executed after the main compensation, it is called Revert-After-Executor.

include::query_executor.adoc[]

include::command_executor.adoc[]

include::revert_before_executor.adoc[]

include::revert_after_executor.adoc[]