=== SagaTransactionTaskThreadPoolTaskExecutor [[saga_discovery_transaction_task_executor]]

`TransactionThreadPool` is the main pool of the StackSaga engine which is responsible for starting the transaction and executing the transaction.

because this thread-pool is used for starting your transaction when it is called the <<saga_template,`SagaTemplate.process()`>> method. after starting the transaction, this thread-pool will handle all the executions of the executors.

IMPORTANT: There are two thread-pools in the StackSaga engine to execute the transactions called xref:#saga_discovery_transaction_task_executor[`TransactionThreadPool`] and  xref:saga_retry_transaction_thread_pool_task_executor.adoc#saga_retry_transaction_thread_pool_task_executor[`RetryTransactionThreadPool`].
the `TransactionThreadPool` is used for executing *new transactions* and, the `RetryTransactionThreadPool` is used for executing the *retrying-transactions*.
Having separate thread-pools ensures the application's resiliency.
Because if the application is full of retrying transactions, it disrupts the new transaction.
You can configure the wight for both thread-pools separately as you prefer.

— In case if you want to customize the default configuration such as pool size, name, queue size and so on, you can update the default configuration as follows:

[source,java]
----
@Component //<1>
public class CustomSagaTransactionTaskThreadPoolTaskExecutor
    implements SagaTransactionTaskThreadPoolTaskExecutor { //<2>

    @Override
    public ThreadPoolTaskExecutor getTaskExecutor() {
        //<3>
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(Runtime.getRuntime().availableProcessors() * 5);
        ...
        return executor;
    }
}
----

<1> Mark the class as a spring `@Component` (bean).
<2> Implement the custom task-executor provider class from `SagaTransactionTaskThreadPoolTaskExecutor` and override the `getTaskExecutor()` method.
<3> Provide your custom task-executor configurations by creating a new instance of https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor.html[`ThreadPoolTaskExecutor`].

NOTE: Even though you change the prefix of the thread-pool when the task-executor is created, the prefix is changed internally as `saga-tx-`  for maintaining the thread-name uniqueness.

'''
