= JDBC Datasource Configuration Properties

[cols="~,~,~,70h"]
|===
|Property Name|Default Value|Type|Description

|`stacksaga.datasource.pool-type` | `shared_pool`  | Enum | StackSaga support tow different connection pools for retrying and general transactions.+
By default `shared_pool` is used for both. but if you want to use two different connection pools you can provide the type as `separate_pool`.
|`maximum-retry-pool-size` | `10`  | int | If you have configured `shared_pool`, then you can configure the maximum pool size for thr *retry-pool*.
|`minimum-retry-idle` | `10`  | int | If you have configured `shared_pool`, then idle pool size for the *retry-pool*
|`ddl-auto` | `update`  | Enum | The database should be updated or creating by dropping when the application is started.
|===

NOTE: Due to StackSaga internally uses HikariCP for managing the connection pool, all other regular configurations can be done according the https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#gear-configuration-knobs-baby[HikariCP Configurations] like username, password, connectionTimeout etc. +
The prefix is `stacksaga.datasource`