=== SagaAdminConnectRestTemplateProvider [[saga_admin_connect_rest_template_provider]]

If you use StackSaga admin feature in your application `SagaAdminConnectRestTemplate` is used for communicating with the admin server.
The default basic configuration has not been implemented for the SSL.
If you want to customize the default configuration for enabling SSL and any additional configurations such as interceptors, filters, and so on, you can update the default configuration as follows:

[source,java]
----
@Component //<1>
public class CustomSagaAdminConnectRestTemplateProvider implements SagaAdminConnectRestTemplateProvider { //<2>

    @Override
    public RestTemplate getRestTemplate(RestTemplateBuilder restTemplateBuilder) {
        //<3>
        return restTemplateBuilder
                //custom SSL
                .setSslBundle(this.getSslBundle())
                //custom header Interceptor
                .additionalInterceptors((request, body, execution) -> {
                    request.getHeaders().put("X-test-header", Collections.singletonList("TEST_VALUE"));
                    return execution.execute(request, body);
                })
                .build();
    }
}
----

<1> Mark the class as a spring `@Component` (bean).
<2> Implement the CustomSagaAdminConnectRestTemplateProvider class from `SagaAdminConnectRestTemplateProvider` and override the `getRestTemplate(RestTemplateBuilder restTemplateBuilder)` method.
<3> Build the RestTemplate object with your own configurations by using `restTemplateBuilder`.

NOTE: It's recommended to use the `RestTemplateBuilder` to build the RestTemplate object because `restTemplateBuilder` contains the basic necessary configurations for communicating with the admin server.
'''
