In the StackSaga ecosystem, few components are working together.
It can be divided as below based on the usage.

* Orchestration service related components
** xref:stacksaga-spring-boot-starter[stacksaga-spring-boot-starter]
** xref:stacksaga-db-support[stacksaga-db-support]
** xref:stacksaga-env-support[stacksaga-env-support]
* xref:agent_service_related_components[Agent service related components]
* xref:stacksaga-cloud-window[StackSaga Cloud-Window]

Here you can see the relationship between them and how they are used in the StackSaga ecosystem.

image:overview/stacksaga-components.drawio.svg[]

[[orchestration_service_related_components]]
== Orchestration service related components

Stacksaga is configured based on the target service that you want to make the service as the Orchestration service.
For instance if you want to configure stacksaga into the order service, you have to add the Orchestration service related components into the `order service`.

[[stacksaga-spring-boot-starter]]
=== `stacksaga-spring-boot-starter` Dependency

`stacksaga-spring-boot-starter` is the core of the framework, and it can be added as a dependency into your project like below.

[source,xml]
----
<dependency>
  <groupId>org.stacksaga</groupId>
  <artifactId>stacksaga-spring-boot-starter</artifactId>
  <version>${org.stacksaga.version}</version>
</dependency>
----

[[stacksaga-db-support]]
=== `stacksaga-db-support` Dependency

StackSaga works with the help of the event-store.
So it requires a one of database implementations for connecting with the target database.
The database implementation is based on your target Orchestration service's database.
For instance, if you want to configure stacksaga into the `order-service`, and the Mysql database is used as the primary database in the `order-service`, you have to add the stacksaga database support mysql implementation called `stacksaga-mysql-support` dependency into the `order service`.

Currently, the following database implementations are available.

* Mysql Database - xref:stacksaga-database-support:mysql-database-support/stacksaga-mysql-support.adoc[stacksaga-mysql-support]
* Cassandra Database - xref:stacksaga-database-support:cassandra-database-support/stacksaga-cassandra-support.adoc[stacksaga-cassandra-support]
* MongoDb Database - `stacksaga-mongodb-support` #Comming soon!#

[[stacksaga-env-support]]
=== `stacksaga-env-support` Dependency

`stacksaga-env-support` Dependency provides the environment related geographical (region, zone, instance ID, etc.) data to the SEC.
Based on where your applications are deployed the `stacksaga-env-support` should be changed.
For instance, if you deploy your `order-service` application in the *eureka* environment(Eureka based service discovery and load balancing), you have to add the `stacksaga-eureka-support` dependency into the `order service`.
And if you want to migrate your `order-service` application to the *kubernetes* environment, you can change the `stacksaga-eureka-support` dependency to the `stacksaga-k8s-support` dependency in the `order service`.

Currently, StackSaga supports for the following environments.

* Eureka based environment - xref:stacksaga-service-discovery-support:eureka-support/stacksaga-eureka-support.adoc[stacksaga-eureka-support]
* Kubernetes environment - xref:stacksaga-service-discovery-support:k8s-support/stacksaga_in_kubernetes.adoc[stacksaga-k8s-support]

[[agent_service_related_components]]
=== Agent service related components

To manage the transaction retrying, you have to build the agent application for the target Orchestration service.
To create an agent-service, you have to choose one of `stacksaga-agent` dependencies based on the target Orchestration service's database.
For instance, if you have configured StackSaga on the `order-service` with the `stacksaga-mysql-support` database, you have to create a `stacksaga-agent` application for the `order-service` by adding the `stacksaga-mysql-agent` dependency.

NOTE: No need to worry about the environment that your agent-application is deployed.
Because all the `stacksaga-agent` implementations supports for all the environments.
You can adjust the agent-application by changing the profile to your target environment.
For instance, if you want to deploy the agent-application in the *kubernetes* environment, you can mention the profile as `k8s` in the property file in your application.

The following stacksaga-agent dependencies are available for the specific databases.

* Mysql Agent - xref:stacksaga-agent:mysql-agent/mysql-stacksaga-agent.adoc[stacksaga-mysql-agent]
* Cassandra Agent - xref:stacksaga-agent:/cassandra-agent/cassandra-agent.adoc[stacksaga-cassandra-agent]
* MongoDb Agent - `stacksaga-mongodb-agent` #Comming soon!#

[[stacksaga-cloud-window]]
=== StackSaga Cloud-Window

Stacksaga Cloud-Window is the platform that you can see the transaction tracing details of the transaction that you made in graphically.
there is nothing to be implemented regarding this component. you can visit https://live.stacksaga.org[live.stacksaga.org] and use it.

////
StackSaga consists of four major components in high-level.

. *StackSaga Framework.* +
StackSaga Framework provides orchestration engine to manage the saga work flows to execute the primary executions, compensating executions, transaction reties, and so on.
Stacksaga framework consists of three major components (dependencies).
** stacksaga-core (stacksaga-starter) +
The core and common features that are required by Saga execution coordinator engine.
** stacksaga-database-support +
The event-store supportive implementation for the saga engine.
It can be chosen as needed based on the database which is used for the service.
If the service that used as orchestration engine is using mysql, then the stacksaga-database-support implementation should be `stacksaga-starter-mysql`.
** StackSaga Environment Support +
The *StackSaga-environment-support* implementation facilitates the management of instance metadata that requires for handling the geographical identification of instances by interacting with the environment like Eureka, Kubernetes and so on.
. *StackSaga Agent*
. *xref:admin:stacksaga-cloud-window.adoc[StackSaga Cloud-Window]*
+
StackSaga cloud-window provides the monitoring facilities of the transactions and manages the security.
////

