In the StackSaga ecosystem, few components are working together.
It can be divided as below based on the usage.

* Orchestration service related components
** xref:stacksaga-spring-boot-starter[stacksaga-spring-boot-starter]
** xref:stacksaga-db-support[stacksaga-db-support]
** xref:stacksaga-env-support[stacksaga-env-support]
* xref:agent_service_related_components[Agent service related components]
* xref:stacksaga-trace-window[StackSaga Trace-Window]

Here you can see the relationship between them and how they are used in the StackSaga ecosystem.

image:overview/stacksaga-diagram-stacksaga-components.svg[alt="stacksaga components overview",title="Stacksaga components overview",width=800]

*Description*

* xref:stacksaga-spring-boot-starter[stacksaga-spring-boot-starter] provides the core features of the StackSaga framework like managing the saga work flows, transaction coordination, idempotency, event sourcing, and so on.
* xref:stacksaga-db-support[stacksaga-db-support] provides the event-store supportive implementation for the StackSaga framework and rest APIs for accessing the tracing details from the StackSaga Trace-Window.
* xref:stacksaga-env-support[stacksaga-env-support] provides the environment related geographical (region, zone, instance ID, etc.) data to the SEC in the cloud environment.
* xref:agent_service_related_components[Agent service] provides the transaction retrying management for the Orchestration service as a separate application.
* xref:stacksaga-trace-window[StackSaga Trace-Window] provides the monitoring facilities of the transactions. (no need to implement due to its hosted in the cloud for you)

See the individual sections for more details.

[[orchestration_service_related_components]]
== Orchestration service related components

Stacksaga is configured based on the target service that you want to make the service as the Orchestration service.
For instance if you want to configure stacksaga into the order service, you have to add the Orchestration service related components into the `order service`.

[[stacksaga-spring-boot-starter]]
=== `stacksaga-spring-boot-starter` Dependency

`stacksaga-spring-boot-starter` is the core of the framework, and it can be added as a dependency into your project like below.

[source,xml]
----
<dependency>
  <groupId>org.stacksaga</groupId>
  <artifactId>stacksaga-spring-boot-starter</artifactId>
  <version>${org.stacksaga.version}</version>
</dependency>
----

`stacksaga-spring-boot-starter` works with the following major components.

* SagaTemplates - Entry point to deal with `stacksaga-spring-boot-starter`.
** xref:stacksaga-sync/saga-templates/saga_template.adoc[]
** xref:stacksaga-sync/saga-templates/reactive_saga_template.adoc[]
* xref:stacksaga-sync/aggregator/aggregator.adoc[Aggregator] - To store the necessary data that is required for the transaction.
* xref:stacksaga-sync/executor/executor_architecture.adoc[Executors] - To create and execute each atomic transactions.

[[stacksaga-db-support]]
=== `stacksaga-db-support` Dependency

StackSaga works with the help of the event-store.
So it requires a one of database implementations for connecting with the target database.
The database implementation is based on your target Orchestration service's database.
For instance, if you want to configure stacksaga into the `order-service`, and the Mysql database is used as the primary database in the `order-service`, you have to add the stacksaga database support mysql implementation called `stacksaga-mysql-support` dependency into the `order service`.

Currently, the following database implementations are available.

* Mysql Database - xref:stacksaga-database-support:mysql-database-support/stacksaga-mysql-support.adoc[stacksaga-mysql-support]
* Cassandra Database - xref:stacksaga-database-support:cassandra-database-support/stacksaga-cassandra-support.adoc[stacksaga-cassandra-support]
* MongoDb Database - `stacksaga-mongodb-support` #Comming soon!#

[[stacksaga-env-support]]
=== `stacksaga-env-support` Dependency

`stacksaga-env-support` Dependency provides the environment related geographical (region, zone, instance ID, etc.) data to the SEC.
Based on where your applications are deployed the `stacksaga-env-support` should be changed.
For instance, if you deploy your `order-service` application in the *eureka* environment(Eureka based service discovery and load balancing), you have to add the `stacksaga-eureka-support` dependency into the `order service`.
And if you want to migrate your `order-service` application to the *kubernetes* environment, you can change the `stacksaga-eureka-support` dependency to the `stacksaga-k8s-support` dependency in the `order service`.

Currently, StackSaga supports for the following environments.

* Eureka based environment - xref:stacksaga-environment-support:eureka-support/stacksaga-env-eureka-support.adoc[stacksaga-eureka-support]
* Kubernetes environment - xref:stacksaga-environment-support:k8s-support/stacksaga_env_k8s_support.adoc[stacksaga-k8s-support]

[[agent_service_related_components]]
=== Agent service related components

To manage the transaction retrying, you have to build the agent application for the target Orchestration service.
To create an agent-service, you have to choose one of `stacksaga-agent` dependencies based on the target Orchestration service's database.
For instance, if you have configured StackSaga on the `order-service` with the `stacksaga-mysql-support` database, you have to create a `stacksaga-agent` application for the `order-service` by adding the `stacksaga-mysql-agent` dependency.

NOTE: No need to worry about the environment that your agent-application is deployed.
Because all the `stacksaga-agent` implementations supports for all the environments.
You can adjust the agent-application by changing the profile to your target environment.
For instance, if you want to deploy the agent-application in the *kubernetes* environment, you can mention the profile as `k8s` in the property file in your application.

The following stacksaga-agent dependencies are available for the specific databases.

* Mysql Agent - xref:stacksaga-sync/stacksaga-agent/mysql-agent/mysql-stacksaga-agent.adoc[stacksaga-mysql-agent]
* Cassandra Agent - xref:stacksaga-sync/stacksaga-agent/cassandra-agent/cassandra-agent.adoc[stacksaga-cassandra-agent]
* MongoDb Agent - `stacksaga-mongodb-agent` #Comming soon!#

[[stacksaga-trace-window]]
=== StackSaga Trace-Window

Stacksaga Trace-Window is the platform that you can see the transaction tracing details of the transaction that you made in graphically.
there is nothing to be implemented regarding this component. you can visit https://trace.stacksaga.org[trace.stacksaga.org] and use it.

== Low-Level Digram (LLD)

Here you can see how the StackSaga Execution Coordinator (SEC) fits into the overall Stacksaga architecture.

image::overview/stacksaga-diagram-SEC-in-stacksaga-framework.svg[alt="StackSaga  StackSaga Execution Coordinator (SEC) in Stacksaga framework"]

. The request comes to the orchestration service, and it is handed off to SEC with the SEC to process them asynchronously.
. SEC will pick up the request and start the execution from the configured starting point.
. Each step will be executed one by one based on the programmatic navigation by keeping the state in the event-store in case of retrying and tracing.
with the help of the stacksaga-database-support module and stacksaga-env-support module(to get the instance's metadata(optional)).
. If there is any primary execution failure, SEC will trigger the compensation executions in reverse order.
. If there is any failure in the compensation execution due to any resource unavailability, the SEC will keep the transaction in retry mode and retry the transaction based on the configured retry policy.
. Configured agent-service frequently checks for the transactions that are in retry mode and retry them by calling the orchestration service's built-in retrying endpoint that is provided by the stacksaga-database-support module.
. Again, the SEC will pick up the request and start the execution from the failed point by restoring the previous state from the event-store.
. Each update of the transaction is saved in the event-store, and the SEC will publish the events to the configured listeners for each transaction state change.
. The administrators can see the tracing details of the transaction graphically by accessing the StackSaga Trace-Window via the in-built endpoints that are provided by the stacksaga-database-support module.

////
StackSaga consists of four major components in high-level.

. *StackSaga Framework.* +
StackSaga Framework provides orchestration engine to manage the saga work flows to execute the primary executions, compensating executions, transaction reties, and so on.
Stacksaga framework consists of three major components (dependencies).
** stacksaga-core (stacksaga-starter) +
The core and common features that are required by Saga execution coordinator engine.
** stacksaga-database-support +
The event-store supportive implementation for the saga engine.
It can be chosen as needed based on the database which is used for the service.
If the service that used as orchestration engine is using mysql, then the stacksaga-database-support implementation should be `stacksaga-starter-mysql`.
** StackSaga Environment Support +
The *StackSaga-environment-support* implementation facilitates the management of instance metadata that requires for handling the geographical identification of instances by interacting with the environment like Eureka, Kubernetes and so on.
. *StackSaga Agent*
. *xref:admin:stacksaga-trace-window.adoc[StackSaga Trace-Window]*
+
StackSaga trace-window provides the monitoring facilities of the transactions and manages the security.
////

