= Stacksaga Kafka Client

== Overview

Stacksaga kafka client is a supportive library for xref:stacksaga-kafka/overview.adoc[Stacksaga Kafka engine] to maintain the standard of xref:#stacksaga-kafka-endpoints[kafka saga endpoints] and validating them.
due to the fact that the stacksaga kafka behave in *request-response* model it is not enough triggering an event to the target service.
the target service also should trigger the *response-event* back to the orchestrator service. that means the target service acts as the publisher and as well as the subscriber.
as a developer you don't need to worry about triggering the *response-event*.
that responsibility is taken by the *Stacksaga Kafka Client,* and it is done behind the scene.

The following duties are done by the Stacksaga kafka client.

* Provides the specifications for creating the xref:#stacksaga-kafka-endpoints[kafka saga endpoints] according to the Stacksaga kafka engine in the target client service.
* Making the response back to the orchestrator service after each invocation.
* Providing immediate retrying facilities in case of retryable exceptions.

`stacksaga-kafka-client` dependency can be added in this way into your target service.

[source,xml]
----
<dependency>
  <groupId>org.stacksaga</groupId>
  <artifactId>stacksaga-kafka-client</artifactId>
  <version>${org.stacksaga.version}</version>
</dependency>
----

As you can see here you have to add the `stacksaga-kafka-client` library for all target service that you want access while processing the entire transaction.

NOTE: if a service acts as *Orchestrator service* by adding `stacksag-kafka-starter`, the `stacksaga-kafka-client` has been added by default.

image::stacksaga-kafka/stacksaga-kafka-client/stacksaga-kafka-engine-stacksaga-engine-vs-satacksaga-client.svg[]

include::stacksaga-kafka-client-endpoints.adoc[]

