= Admin Communication With Event-store [[stack_saga_admin_connect_with_event_store]]

image:architecture_stacksaga_how_admin_dashboard_access_stacksaga_endpoint.drawio.svg[alt="StackSaga High-level architecture",height=300]

. Admin sends the request to access the event-store data from the admin-dashboard (`+/stacksaga/**+`) with the admin-user credentials.
. spring API-gateway catches the request and check the mapping. if the request is starting prefixed with `+/stacksaga+`, the request goes through the *StackSaga Shield*'s filter. then the filter will communicate with the stacksaga admin server with the admin-user credentials and also with the Api-Gateway-user credentials.
. StackSaga admin received the request and checks the both credentials.
. StackSaga admin sends the response the credentials are valid or not.
v If the request credentials are validated, Api-Gateway sends the request to one of available service instances (x-Service). +
. The service will rerun the data set to the incoming request.
(The endpoint will be provided by the StackSaga connector.)
