= Aggregator Version Casting

== Overview

All the applications will be updated by changing their versions from time to time.
When a new version is deployed, the old version will be replaced by the new version (if you are not going to use service-mesh).
But in the event-based architecture, some events can have been waiting to be executed when the new version is being deployed or after deployed as well.

Then the old event should be mapped with the new version.
That means by using the old serialized aggregator objects that are in the event-store should be able to create a new aggregator object.

So, if you don't consider the old version’s events that might be in the event-store, when developing the new version, the events will be conflicted or crashed while mapping the old event to the new aggregator version.
Because the old version's events are going to be executed by using the new aggregator.

.Event rebuilding by the engine for transaction retrying.
image:stacksaga-diagram-event-rebuiding.drawio.svg[alt="stacksaga diagram event rebuilding"]

include::aggregator_oriented_casting_architecture.adoc[]

Related Topics

* xref:replay-transaction.adoc[Transaction Replay]
* xref:aggregator_versioning.adoc[Aggregator Versioning]


// include::executor_oriented_casting_architecture.adoc[]
