= Stacksaga Environment Support

== Overview

The Stacksaga Environment Support module suite provides essential metadata and utilities to accurately identify the runtime environment of the orchestrator application, including zone, region, and instance ID etc.
This metadata enhances the Stacksaga engine's observability and tracing by enabling structured transaction storage, facilitating efficient filtering and searching based on environment attributes, and supporting targeted retries by agent services.

Here you can see where the stacksaga environment support modules fit into the overall Stacksaga architecture.

image::stacksaga-environment-support:stacksaga-diagram-stacksaga-components-environment-support.svg[]

NOTE: While deployment of the orchestrator application is possible without environment support modules, their usage is strongly recommended to maximize observability and tracing.
In the absence of these modules, Stacksaga defaults to generic environment values (e.g., `default-zone`, `default-region`), which avoid distribution of transactions across regions.

Currently, StackSaga supports the following environments:

|===
| Environment Type | Description

| xref:stacksaga-environment-support:eureka-support/stacksaga-env-eureka-support.adoc[`stacksaga-env-eureka-support`]
| Environments using Eureka for service discovery.

| xref:stacksaga-environment-support:k8s-support/stacksaga_env_k8s_support.adoc[`stacksaga-env-k8s-support`]
| Environments running on Kubernetes clusters.

| `stacksaga-env-consul-support`
| coming soon...

|===