=== Creating OrderController (API Endpoint).

As per the xref:quick-examples:stacksaga-demo.adoc#demo_diagram[diagram], the request comes to the `/order/place` endpoint.
And also the request is transferred to the SEC by accessing the `SagaTemplate`.

[[orderController_source]]
[source,java]
----
package org.example.api;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.example.aggregator.PlaceOrderAggregator;
import org.example.dto.PlaceOrderDto;
import org.example.handler.PlaceOrderHandler;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;

@RestController
@RequestMapping("/order")
@RequiredArgsConstructor
@Slf4j
public class OrderController {

    //<1>
    private final PlaceOrderHandler placeOrderHandler;

    //<2>
    @PostMapping
    @ResponseStatus(HttpStatus.ACCEPTED)
    public PlaceOrderDto.ResponseBody createOrder(@RequestBody PlaceOrderDto.RequestBody requestBody) {
        log.debug("requestBody:{}", requestBody);
        //<3>
        final PlaceOrderAggregator placeOrderAggregator = new PlaceOrderAggregator();
        placeOrderAggregator.setUserId(requestBody.getUserId());
        placeOrderAggregator.setItems(requestBody.getItems());
        placeOrderAggregator.setAmount(
                requestBody.getItems()
                        .stream()
                        .map(orderItem -> orderItem.getItemPrice() * orderItem.getQty())
                        .mapToDouble(Double::doubleValue)
                        .sum()
        );
        placeOrderAggregator.setHasRevertError(requestBody.getHasRevertError());
        placeOrderAggregator.getExecutions().add("INIT:" + LocalDateTime.now());
        log.debug("placeOrderAggregator:{}", placeOrderAggregator);
        //<4>
        final String transactionId = this.placeOrderHandler.process(placeOrderAggregator);
        return PlaceOrderDto.ResponseBody.builder()
                .orderId(transactionId)
                .message("order has been submitted successfully")
                .build();
    }
    //<5>
    @GetMapping("/status")
    public List<String> getCurrentStatus(@RequestParam("order_id") String orderId) {
        return this.placeOrderHandler.getAggregatorState(orderId);
    }
}
----

<1> Autowire the xref:creating-stacksaga-handler-class.adoc#PlaceOrderHandler[`PlaceOrderHandler`] for handing over the request to the framework for further execution.

<2> Create your endpoint to receive the place order request.

<3> Create a `PlaceOrderAggregator` object with the initial data (initial payload) to pass the request to the SEC.

<4> Call the `process` method in the `PlaceOrderHandler` to process the request and get the `transactionId` to build the repose.

<5> Create a method to get the status of the transaction from the event-store and invoke the xref:creating-stacksaga-handler-class.adoc#PlaceOrderHandler[`getAggregatorState`] method.
