=== Creating StockUpdateExecutor (Command-Executor)

`StockUpdateExecutor` is responsible for updating (deducting) the stock by connecting with the utility *inventory-service*.
After deducting the stock to place the order, if an error occurs that deducted stock should be restored.
Because the order will be canceled.
That means that the execution has Compensating.
Therefore, the executor should be a `Command-Executor`

[source,java]
----
// <1>
@SagaExecutor(executeFor = "stock-service", liveCheck = false, value = "StockUpdateExecutor")
@RequiredArgsConstructor
public class StockUpdateExecutor implements CommandExecutor<PlaceOrderAggregator> { // <2>

    private final StockService stockService;

    @Override
    public ProcessStepManager<PlaceOrderAggregator> doProcess(
            PlaceOrderAggregator currentAggregator,
            ProcessStepManagerUtil<PlaceOrderAggregator> stepManager,
            String idempotencyKey
    ) throws RetryableExecutorException, NonRetryableExecutorException {
        //<3>
        currentAggregator.getExecutions().add(this.getClass().getSimpleName()+":"+ LocalDateTime.now());
        // <4>
        this.stockService.updateStock(
                UpdateStockDto.RequestBody
                        .builder()
                        .orderId(currentAggregator.getAggregatorTransactionId())
                        .items(currentAggregator
                                .getItems()
                                .stream()
                                .collect(
                                        Collectors.toMap(
                                                OrderItem::getItemId,
                                                OrderItem::getQty
                                        )
                                )
                        )
                        .build()
        );
        // <5>
        return stepManager.next(MakePaymentExecutor.class, OrderStatus.UPDATED_STOCK);
    }

    @Override
    public SagaExecutionEventName doRevert(
            NonRetryableExecutorException processException,
            PlaceOrderAggregator finalAggregatorState,
            RevertHintStore revertHintStore,
            String idempotencyKey
    ) throws RetryableExecutorException {
        // <6>
        this.stockService.restoreStock(
                RestoreStockDto.RequestBody
                        .builder()
                        .reason(processException
                                .get("reason")
                                .orElse("")
                        )
                        .build()
        );
        // <7>
        revertHintStore.put(
                String.valueOf(System.currentTimeMillis()),
                this.getClass().getSimpleName() + ":doRevert"
        );
        // <8>
        return OrderStatus.RESTORED_STOCK;
    }
}
----

*Highlights*

<1> Annotate the `StockUpdateExecutor` class as a `SagaExecutor` by using `@SagaExecutor` annotation.
+
executeFor:: executeFor is the target service’s name.
value::
value is the bean name of the executor.

<2> Implement the `StockUpdateExecutor` from the `CommandExecutor` by passing the target Aggregator.

<3> Adding the current executor to the Executions list to keep track via the StackSaga Cloud-Window.
(This part is only for logging purposes to understand).

<4> updating the stock by invoking the StockService's `updateStock()` method. the `orderId` and `items` are passed accessing from the `currentAggregator`.

<5> Navigates the execution by using `stepManager` to the next executor called `MakePaymentExecutor`.
And also passed the status as `UPDATED_STOCK`.

<6> Calling the StockService's `restoreStock()` method to restoring the items that has been reduced in the `doProcess()` method.
To restore the Stock, we have to pass a reason.
Due to we have put a reason all the possible times when an `NonRetryableExecutorException` is occurred in `doProcess` executions.
If the value doesn't exist in the exception object we have passed just empty `String` there.

<7> Update the hint-store object by adding current millisecond and the revert method name with the executor name while the revert process.  +
In your real application, xref://[the hint-store] can be used for adding some data regarding the revert process.
It can be accessed from the next revert process.

<8> Returns the status as `RESTORED_STOCK` finally.

=== Creating StockService

We called the `StockService` in the `StockUpdateExecutor`.
The service `StockService` class is responsible for updating the stock or if there is an error, restore the stock by connecting with the utility `stock-service`.
So let's create the service now.

[source,java]
----
@Service
@RequiredArgsConstructor
public class StockService {

    private final RestTemplate restTemplate;

    public void updateStock(UpdateStockDto.RequestBody requestBody)
            throws
            RetryableExecutorException, NonRetryableExecutorException {
        try {
            // <1>
            this.restTemplate.put(
                    "http://stock-service/stock",
                    requestBody
            );
        } catch (HttpServerErrorException ex) { // <2>
            // This exception is thrown for HTTP 5xx errors (Server errors)
            // You can handle specific HTTP error codes here
            if (ex.getStatusCode().equals(HttpStatus.INTERNAL_SERVER_ERROR)) {
                throw ex;
            } else {
                //502 , 503, 504, 509 etc.
                throw RetryableExecutorException.buildWith(ex).build();
            }
        } catch (RestClientException ex) { // <3>
            // This exception is a generic RestClientException
            // Handle other types of exceptions here
            throw ex;
        }

    }

    public void restoreStock(RestoreStockDto.RequestBody requestBody) throws RetryableExecutorException {
        try {
            // <4>
            this.restTemplate.put(
                    "http://stock-service/stock/restore",
                    requestBody
            );
        } catch (HttpServerErrorException ex) { // <5>
            // This exception is thrown for HTTP 5xx errors (Server errors)
            // You can handle specific HTTP error codes here
            if (ex.getStatusCode().equals(HttpStatus.INTERNAL_SERVER_ERROR)) {
                throw ex;
            } else {
                //502 , 503, 504, 509 etc.
                throw RetryableExecutorException.buildWith(ex).build();
            }
        } catch (RestClientException ex) { // <6>
            // This exception is a generic RestClientException
            // Handle other types of exceptions here
            throw ex;
        }
    }
}
----

This service is also pretty much the same as the service that has been created so far.

*Highlights*

<1> Call the endpoint to update the stock.

<2> Catch the https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[*5xx*] HTTP errors to determine if the exception is a `NonRetryableExecutorException` or `RetryableExecutorException`.
Most probably 5xx errors can be retried, but there are some cases it cannot.

<3> Catch the other exceptions (with 4xx errors as well).

<4> Call the endpoint to restore the updated stock.

<5> Catch the https://en.wikipedia.org/wiki/List_of_HTTP_status_codes[*5xx*] HTTP errors to determine if the exception is a `NonRetryableExecutorException` or `RetryableExecutorException`.
Most probably 5xx errors can be retried, but there are some cases it can not.

<6> Catch the other exceptions (with 4xx errors as well).

