[[creating_order_initialize_executor]]
=== Creating OrderInitializeExecutor

You know that the request comes to the `OrderController`
and the request is transferred to the `OrderInitializeExecutor` as the first step.
And next, we want to decide what OrderInitializeExecutor class type should be.
That means that there are two executor types in StackSga called xref:framework:command_executor.adoc[CommandExecutor] and xref:framework:query_executor.adoc[QueryExecutor].

The OrderInitializeExecutor should be a command-executor because if a failure occurred at some point after executing the order initialization process, it should be recovered again.
Here we mark the order as canceled.

.https://github.com/stacksaga/stacksaga-examples/blob/main/stacksaga-demo-for-kubernetes/order-service/src/main/java/org/example/executor/OrderInitializeExecutor.java[icon:github[role=black,size=2x] OrderInitializeExecutor.class]
[source,java]
----
// <1>
@SagaExecutor(executeFor = "order-service", liveCheck = false, value = "OrderInitializeExecutor")
@RequiredArgsConstructor
public class OrderInitializeExecutor implements CommandExecutor<PlaceOrderAggregator> { // <2>

    // <3>
    private final OrderService orderService;
    private final ObjectMapper objectMapper;

    @Override // <4>
    public ProcessStepManager<PlaceOrderAggregator> doProcess(PlaceOrderAggregator currentAggregator, ProcessStepManagerUtil<PlaceOrderAggregator> stepManager) throws RetryableExecutorException, NonRetryableExecutorException {
        try {
            currentAggregator.getExecutions().add(this.getClass().getSimpleName() + ":" + LocalDateTime.now());
            // <5>
            this.orderService.initialize(
                    OrderEntity
                            .builder()
                            .orderId(currentAggregator.getAggregatorTransactionId())
                            .userId(currentAggregator.getUserId())
                            .createAt(LocalDateTime.now())
                            .isCancelled(false)
                            .items(objectMapper.writeValueAsString(currentAggregator.getItems()))
                            .build()
            );
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
        // <6>
        return stepManager.next(UserDetailExecutor.class, OrderStatus.INITIALIZED_ORDER.name());
    }

    @Override // <4>
    public String doRevert(NonRetryableExecutorException processException, PlaceOrderAggregator finalAggregatorState, RevertHintStore revertHintStore) throws RetryableExecutorException {
        // <7>
        this.orderService.cancelOrder(finalAggregatorState.getAggregatorTransactionId());
        // <8>
        revertHintStore.put(
                String.valueOf(System.currentTimeMillis()),
                this.getClass().getSimpleName() + ":doRevert"
        );
        // <9>
        if (finalAggregatorState.getHasRevertError()) {
            throw new RuntimeException("dummy error for revert-failed.");
        }
        // <10>
        return OrderStatus.CANCELED_ORDER.name();
    }
}
----

<1> Annotate the `OrderInitializeExecutor` class as a `SagaExecutor` by using `@SagaExecutor` annotation.
+
Read more about xref:framework:saga_executors.adoc#saga_executors[`@SagaExecutor`] annotation.
<2> The class has been extended from the `CommandExecutor`.
+
Read more about xref:framework:saga_executors.adoc#command_executor[`CommandExecutor`] annotation.

<3> Autowire the https://github.com/stacksaga/stacksaga-examples/blob/main/stacksaga-demo-for-kubernetes/order-service/src/main/java/org/example/service/internal/OrderService.java[`OrderService`] service to make the execution.
(`ObjectMapper` has been Autowired just for getting the JSON string)
<4> Overridden the `doProcess` and `doRevert` methods.

<5> Calling the initialize-method to invoke the execution.
(This method is invoked by the framework with different thread-pool.)

<6> After invoking the execution successfully, `stepManager.next` command guides the framework what is the next execution after this execution.
Our next execution should be make