=== Creating OrderController (API Endpoint).

As per the xref:quick-examples:stacksaga-demo.adoc#demo_diagram[diagram], the request comes to the `/order/place` endpoint.
And also it is called to the `PlaceOrderHandler` to transfer the request to the SEC.

[[orderController_source]]
[source,java]
----
package org.example.api;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.example.aggregator.PlaceOrderAggregator;
import org.example.dto.PlaceOrderDto;
import org.example.handler.PlaceOrderHandler;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;

@RestController
@RequestMapping("/order")
@RequiredArgsConstructor
@Slf4j
public class OrderController {

    //<1>
    private final PlaceOrderHandler placeOrderHandler;

    //<2>
    @PostMapping
    @ResponseStatus(HttpStatus.ACCEPTED)
    public PlaceOrderDto.ResponseBody createOrder(@RequestBody PlaceOrderDto.RequestBody requestBody) {
        log.debug("requestBody:{}", requestBody);
        //<3>
        final PlaceOrderAggregator placeOrderAggregator = new PlaceOrderAggregator();
        placeOrderAggregator.setUserId(requestBody.getUserId());
        placeOrderAggregator.setItems(requestBody.getItems());
        placeOrderAggregator.setAmount(
                requestBody.getItems()
                        .stream()
                        .map(orderItem -> orderItem.getItemPrice() * orderItem.getQty())
                        .mapToDouble(Double::doubleValue)
                        .sum()
        );
        //this value is set for testing purposes only. (to check the revert error in StackSaga Cloud-Window)
        placeOrderAggregator.setHasRevertError(requestBody.getHasRevertError());
        placeOrderAggregator.getExecutions().add("INIT:" + LocalDateTime.now());
        log.debug("placeOrderAggregator:{}", placeOrderAggregator);

        //<4>
        final String transactionId = this.placeOrderHandler.process(placeOrderAggregator);
        return PlaceOrderDto.ResponseBody.builder()
                .orderId(transactionId)
                .message("order has been submitted successfully")
                .build();
    }

    //<5>
    @GetMapping("/status")
    public List<String> getCurrentStatus(@RequestParam("order_id") String orderId) {
        return this.placeOrderHandler.getAggregatorState(orderId);
    }
}
----

<1> Autowire the `PlaceOrderHandler` that we created.

<2> Create the endpoint to receive the place order request.

<3> Create a `PlaceOrderAggregator` object with the initial data (initial payload) to pass the request to the SEC.

<4> Call the `process` method in the `PlaceOrderHandler` to process the request and get the `transactionId` to build the repose.

<5> Create a method to get the status of the transaction from the event-store and invoke the xref:creating-stacksaga-handler-class.adoc#PlaceOrderHandler[`getAggregatorState`] method.

NOTE: `PlaceOrderDto.RequestBody` and `PlaceOrderDto.ResponseBody` has been defined in the https://github.com/stacksaga/stacksaga-examples/tree/main/stacksaga-demo-default/order-service/src/main/java/org/example/dto[`org.example.dto`] package.