== Creating API-Cloud-Gateway

Now we are going to create the api-cloud-gateway.

image:admin:stacksaga-example-stacksaga-spring-cloud-api-gateway-demo-hight-level-2.drawio.svg[]

Same as before, visit to the https://start.spring.io/[spring initializr] and create a new project with the following dependencies.

* spring-boot-starter-webflux
* spring-cloud-starter-gateway
* spring-cloud-starter-netflix-eureka-client

IMPORTANT: You don't want to worry about StackSaga things because StackSaga doesn't involve with the API-Gateway.
But to avoid the cross-origin restrictions, you have to xref://[allow the cross-requests] for the Admin-Dashboard URL(s).

The pom.xml file will be like below.

[source,xml]
.pom.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>api-gateway</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>api-gateway</name>
    <description>api-gateway</description>
    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>

        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
----

To enable the Discovery client, annotate the main class by `@EnableDiscoveryClient` like below.
[source,java]
----
package com.example.apigateway;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@SpringBootApplication
@EnableDiscoveryClient
public class ApiGatewayApplication {
    public static void main(String[] args) {
        SpringApplication.run(ApiGatewayApplication.class, args);
    }
}
----

Next, let's update the configuration file.

[source,yaml]
.application.yaml
----
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/ # <1>
  instance:
    hostname: localhost
    # <2>
    instance-id: ${spring.application.name}:${random.uuid}
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        # <3>
        cors-configurations:
          '[/*/stacksaga/**]':
            allowedOrigins:
              - "http://localhost:4444"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        # <4>
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      discovery:
        locator:
          # <5>
          enabled: true
          # <6>
          lower-case-service-id: true
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    author: mafei
    name: ${spring.application.name}
    version: 1.0.0

----

*Highlights*

<1> Provide the eureka service registry URL.
<2> Due to the api gateway also a one eureka clients, you have to mention how it would be the instance id when the api gateway is registered with eureka service.

<3> To avoid the cross-origin restrictions, you can permit the Admin-Dashboard URL.
If you have a list of Admin-Dashboard URLs, you provide all.
It permits all the requests for this pattern.
/*/stacksaga/**

<4> To avoid duplicate response headers exceptions, you can add these filters. (https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway-server-mvc/filters/deduperesponseheader.html[Read spring doc])


<5> Flag that enables DiscoveryClient gateway integration. (https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/the-discoveryclient-route-definition-locator.html[Read spring doc])

<6> Option to lower case serviceId in predicates and filters, defaults to false.
Useful with eureka when it automatically uppercases serviceId.
So MYSERIVCE, would match /myservice/** (https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/appendix.html[Read spring doc])

