==== Order-Service Overview.

You know that we have to access more services besides this `order-service` to fully complete the entire place-order request.
To access those services in general, you would use *service-layer* and call those services manually by using any httpclient like RestTemplate, Feign client, Okhttp, and so on.
Instead of that manual unorganized way, StackSaga offers better wrapper blocks for each execution.
It is called as `executors`.

> Read the xref://[reference documentation]
to have a better understanding and best practices regarding the `SagaExecutors`.

According to the xref://[Saga design pattern], you know that we should have a compensation process for all the execution (All the executions that make some changes in a database).
Due to the fact that the StackSaga framework is one of Saga implementations, it should be provided the primary execution and also a compensation execution to make a compensation when the entire process is failed at any point.

Based on having a compensation or not, the executors are two types called `command-executor` and `query-executor`.
`command-executor` have both primary execution and the compensation execution.
If it is `query-executor`, it has only primary execution.

==== How StackSaga combines with Controller Service and Repository architecture?

In spring applications we follow `controller`, `service` and `repository` layered architecture.
StackSaga suggest another middle layer between the `controller` layer and the `service` layer called #`executor-layer`#.
The `executor-layer` is the place the executors are created.
Let's see step by step how StackSaga involves the process.

Here you can see the entire process in a diagram from based on the order-service (orchestrator-service).

image:stacksaga-example-executors-architecture-in-order-service.drawio.svg[alt="stacksaga microservice example executors architecture in order service"]

In brief client makes an order place request and the request comes to the order-service via the api-cloud-gateway.
And then we initialize a special object called `Aggregator`
and it is handed over to the SEC (Saga Execution coordinator), and the SEC will handle the entire execution by executing each every atomic execution.
The atomic executions have been provided inside the executors.

Here you can see the summarized table for your convenience.

[.scrollable]
--
[cols=".no-wrap, .normal, .no-wrap, .no-wrap, .no-wrap, .no-wrap"]
|===
|Executor Class Name| Execution_Requirement | Target_Service | Type | Process-Execution |  Revert-Execution

|xref://[`OrderInitializeExecutor`]
|Initialize the order at the first.
|`order-service`
|[.badge-yellow]*COMMAND_EXECUTOR*
|`initializeOrder()`
|`cancelOrder()`

|xref://[`UserDetailExecutor`]
|Fetch the user's details
|`user-service`
|[.badge-green]*QUERY_EXECUTOR*
|`getUserDetails`
| -

|xref://[`PreAuthExecutor`]
|Make the Pre-Auth process.
|`payment-service`
|[.badge-yellow]*COMMAND_EXECUTOR*
|`makePreAuth()`
|`releasePreAuth()`

|xref://[`StockUpdateExecutor`]
|Update the stock from the store.
|`stock-service`
|[.badge-yellow]*COMMAND_EXECUTOR*
|`updateStock()`
|`restoreStock()`

|xref://[`MakePaymentExecutor`]
|Finalize the order by making the real payment.
|`payment-service`
|[.badge-yellow]*COMMAND_EXECUTOR*
|`makePayment()`
| ?

|===

--
