= Quick Start
:keywords: satcksaga microservice,spring boot saga,spring cloud microservice saga, saga design pattern,saga orchestration spring boot
:description: spring boot stacksaga quick start demo

[[Overview]]
== Overview

This guide demonstrates how to set up and run a microservice using the StackSaga framework with minimal configuration.
It focuses on a common use case where a microservice communicates with multiple other microservices to fulfill a single business logic.

=== Use Case: Placing an Order

In this scenario, we have a microservice called *Order Service*, which needs to interact with the following microservices to place an order successfully:

Payment Service:: Handles payment processing.

Stock Service:: Manages inventory checks and updates.

User Service:: Retrieves and verifies user information.

The goal is to demonstrate how the StackSaga framework simplifies the process of coordinating communication between these microservices to implement the business logic for order placement.

=== Prerequisites

Before you begin, ensure the following:
=== Creating the orchestrator service

* Java Development Environment: JDK 17 or higher is installed.

* Database: Mysql or any database that supports stacksaga.
(This example uses Mysql)

* Microservices Setup: Basic implementations of Order Service, Payment Service, Stock Service, and User Service are available.

The steps are as follows.

* xref:creating_the_orchestrator_service[Creating the orchestrator service (order-service).]
* xref:adding_stacksaga_dependencies_to_the_existing_order_service_project[Adding required stacksaga dependencies]
* Create an aggregator class
* Create the executors
* Run and test

[[creating_the_orchestrator_service]]
=== Creating the orchestrator service

As the first step, let's create the orchestrator service (order-service).
It is nothing but a spring boot web application with mysql-database support.

Go to the https://start.spring.io[spring initializr] and create a new project with the following dependencies.

. Spring Web
. Lombok (for avoiding boilerplate code)
. MySQL Driver (For using mysql database as the event-store)

[[adding_stacksaga_dependencies_to_the_existing_order_service_project]]
=== Adding stacksaga dependencies to the existing order-service project.

After creating the project, it is necessary to add the required stacksaga dependencies in the dependencies section.

stacksaga-spring-boot-starter::
The core of the framework.
+
[source,properties]
----
<dependency>
   <groupId>org.stacksaga</groupId>
   <artifactId>stacksaga-spring-boot-starter</artifactId>
   <version>1.0.0</version>
</dependency>
----

stacksaga-mysql-support::
The Mysql database supports implementation for the framework.
+
[source,properties]
----
<dependency>
   <groupId>org.stacksaga</groupId>
   <artifactId>stacksaga-mysql-support</artifactId>
   <version>1.0.0</version>
</dependency>
----



