= Quick Start
:keywords: satcksaga microservice,spring boot saga,spring cloud microservice saga, saga design pattern,saga orchestration spring boot
:description: spring boot stacksaga quick start demo

[[Overview]]
== Overview

This guide demonstrates how to set up and run a microservice using the StackSaga framework with minimal configuration.
It focuses on a common use case where a microservice communicates with multiple other microservices to fulfill a single business logic.

=== Use Case: Placing an Order

In this scenario, we have a microservice called *Order Service*, which needs to interact with the following microservices to place an order successfully:

Payment Service:: Handles payment processing.

Stock Service:: Manages inventory checks and updates.

User Service:: Retrieves and verifies user information.

The goal is to demonstrate how the StackSaga framework simplifies the process of coordinating communication between these microservices to implement the business logic for order placement.

=== Prerequisites

Before you begin, ensure the following:
=== Creating the orchestrator service

* Java Development Environment: JDK 17 or higher is installed.

* Database: Mysql or any database that supports stacksaga.
(This example uses Mysql)

* Microservices Setup: Basic implementations of Order Service, Payment Service, Stock Service, and User Service are available.

The steps are as follows.

* xref:creating_the_orchestrator_service[Creating the orchestrator service (order-service).]
* xref:adding_stacksaga_dependencies_to_the_existing_order_service_project[Adding required stacksaga dependencies and update the required configuration properties.]
* xref:creating_an_aggregator[Creating an aggregator]
* xref:creating_executors[Creating the executors]
* xref:creating_executors[Creating the endpoint]
* Run and test

[[creating_the_orchestrator_service]]
=== Creating the orchestrator service

As the first step, let's create the orchestrator service (order-service).
It is nothing but a spring boot web application with mysql-database support.

Go to the https://start.spring.io[spring initializr] and create a new project with the following dependencies.

. Spring Web
. Lombok (for avoiding boilerplate code)
. MySQL Driver (For using mysql database as the event-store)

[[adding_stacksaga_dependencies_to_the_existing_order_service_project]]
=== Adding stacksaga dependencies and update the required configuration properties.

After creating the project, it is necessary to add the required stacksaga dependencies in the dependencies section.

stacksaga-spring-boot-starter:: The core of the framework.

[source,xml]
----
<dependency>
   <groupId>org.stacksaga</groupId>
   <artifactId>stacksaga-spring-boot-starter</artifactId>
   <version>1.0.0</version>
</dependency>
----

stacksaga-mysql-support:: The Mysql database supports implementation for the framework.

[source,xml]
----
<dependency>
   <groupId>org.stacksaga</groupId>
   <artifactId>stacksaga-mysql-support</artifactId>
   <version>1.0.0</version>
</dependency>
----

Then update the required configuration properties in the `applocation.yml` or `application.properties` file.

[source,yaml]
----
spring:
  application:
    name: order-service #<1>
stacksaga:
  enable: true #<2>
  component-scan: demo.quickdemo.aggregators #<3>
  app-release-version: 1.0.0  #<4>
  datasource: #<5>
    jdbc-url: jdbc:mysql://localhost:3306/stacksaga_event_store?createDatabaseIfNotExist=true
    username: database_username
    password: database_password
    driver-class-name: com.mysql.cj.jdbc.Driver
----

<1> The name of the application is required for stacksaga
<2> Enable stacksaga framework
<3> The package path of the aggregators that are localed in.
<4> The application release version
<5> The database configuration for accessing the mysql database as the event-store.

[[creating_an_aggregator]]
=== Creating an aggregator

Creating an xref:architecture:aggregator.adoc[Aggregator] is one of the main steps in the stacksaga framework implementation.
Because it is the container that holds the states of each execution's data until the transaction is completed.

create the aggregator class in the `demo.quickdemo.aggregators` package with the fields that you want to store the data while the entire transaction.

PlaceOrderAggregator.java::

[source,java]
----
package demo.quickdemo.aggregators;

import lombok.*;
import org.stacksaga.Aggregator;
import org.stacksaga.SagaSerializable;
import org.stacksaga.annotation.SagaAggregator;
import org.stacksaga.annotation.SagaAggregatorVersion;

@SagaAggregator(
        version = @SagaAggregatorVersion(major = 1, minor = 0, patch = 0),
        name = "PlaceOrderAggregator",
        sagaSerializable = PlaceOrderAggregatorSagaSerializable.class
)
@Getter
@Setter
public class PlaceOrderAggregator extends Aggregator {
    private String orderId;
    private double amount;
    private String userId;
    private boolean isPaid;
    private String paymentId;

    public PlaceOrderAggregator() {
        super(PlaceOrderAggregator.class);
    }

}

class PlaceOrderAggregatorSagaSerializable extends SagaSerializable<PlaceOrderAggregator> {
    public PlaceOrderAggregatorSagaSerializable() {
        this.put("Sample-1", new PlaceOrderAggregator());
    }
}
----

[[creating_executors]]
=== Creating executors

Create the executors in the `demo.quickdemo.executors` package.
For this quick-start example, four executors are created to make individual atomic executions to the relevant services.

. *xref:PlaceOrderInitExecutor[PlaceOrderInitExecutor]* for *order-service* (itself)
. *xref:GetUserDetailsExecutor[GetUserDetailsExecutor]* for *user-service*
. *xref:MakePaymentExecutor[MakePaymentExecutor]* for *payment-service*
. *xref:StockUpdateExecutor[StockUpdateExecutor]* for *stock-service*

[[PlaceOrderInitExecutor]]
==== PlaceOrderInitExecutor

[source,java]
----
package demo.quickdemo.executors;

import demo.quickdemo.aggregators.PlaceOrderAggregator;
import lombok.SneakyThrows;
import org.stacksaga.ProcessStepManager;
import org.stacksaga.ProcessStepManagerUtil;
import org.stacksaga.RevertHintStore;
import org.stacksaga.annotation.SagaExecutor;
import org.stacksaga.core.SagaExecutionEventName;
import org.stacksaga.exception.RetryableExecutorException;
import org.stacksaga.exception.execution.NonRetryableExecutorException;
import org.stacksaga.executor.CommandExecutor;

import java.util.Random;

@SagaExecutor(
        executeFor = "order-service",
        value = "PlaceOrderInitExecutor"
)
public class PlaceOrderInitExecutor implements CommandExecutor<PlaceOrderAggregator> {

    @SneakyThrows
    @Override
    public ProcessStepManager<PlaceOrderAggregator> doProcess(
            PlaceOrderAggregator currentAggregator,
            ProcessStepManagerUtil<PlaceOrderAggregator> stepManager,
            String idempotencyKey
    ) throws RetryableExecutorException, NonRetryableExecutorException {
        // TODO: execute place order process here
        Thread.sleep(new Random().nextLong(1000, 3000));
        {
            //updates the aggregator with the order id
            currentAggregator.setOrderId(currentAggregator.getAggregatorTransactionId());
        }
        return stepManager.next(GetUserDetailsExecutor.class, () -> "INITIATED_ORDER");
    }

    @Override
    public SagaExecutionEventName doRevert(NonRetryableExecutorException processException,
                                           PlaceOrderAggregator finalAggregatorState,
                                           RevertHintStore revertHintStore,
                                           String idempotencyKey
    ) throws RetryableExecutorException {

        // TODO: execute place order revert process here
        return () -> "ORDER_CANCELLED";
    }
}
----

[[GetUserDetailsExecutor]]
==== GetUserDetailsExecutor

[source,java]
----
package demo.quickdemo.executors;

import demo.quickdemo.aggregators.PlaceOrderAggregator;
import lombok.SneakyThrows;
import org.stacksaga.ProcessStepManager;
import org.stacksaga.ProcessStepManagerUtil;
import org.stacksaga.annotation.SagaExecutor;
import org.stacksaga.exception.RetryableExecutorException;
import org.stacksaga.exception.execution.NonRetryableExecutorException;
import org.stacksaga.executor.QueryExecutor;

import java.util.Random;

@SagaExecutor(
        executeFor = "user-service",
        value = "GetUserDetailsExecutor"
)
public class GetUserDetailsExecutor implements QueryExecutor<PlaceOrderAggregator> {

    @SneakyThrows
    @Override
    public ProcessStepManager<PlaceOrderAggregator> doProcess(
            PlaceOrderAggregator currentAggregator,
            ProcessStepManagerUtil<PlaceOrderAggregator> stepManager,
            String idempotencyKey
    ) throws RetryableExecutorException, NonRetryableExecutorException {

        // TODO: Get user details from user-service
        Thread.sleep(new Random().nextLong(1000, 3000));
        {
            //updates the aggregator with the user details
            currentAggregator.setUserId("mafei");
        }
        return stepManager.next(MakePaymentExecutor.class, () -> "PLACED_ORDER");
    }
}
----

[[MakePaymentExecutor]]
==== MakePaymentExecutor

[source,java]
----
package demo.quickdemo.executors;

import demo.quickdemo.aggregators.PlaceOrderAggregator;
import lombok.SneakyThrows;
import org.stacksaga.ProcessStepManager;
import org.stacksaga.ProcessStepManagerUtil;
import org.stacksaga.RevertHintStore;
import org.stacksaga.annotation.SagaExecutor;
import org.stacksaga.core.SagaExecutionEventName;
import org.stacksaga.exception.RetryableExecutorException;
import org.stacksaga.exception.execution.NonRetryableExecutorException;
import org.stacksaga.executor.CommandExecutor;

import java.util.Random;

@SagaExecutor(
        executeFor = "payment-service",
        value = "MakePaymentExecutor"
)
public class MakePaymentExecutor implements CommandExecutor<PlaceOrderAggregator> {

    @SneakyThrows
    @Override
    public ProcessStepManager<PlaceOrderAggregator> doProcess(
            PlaceOrderAggregator currentAggregator,
            ProcessStepManagerUtil<PlaceOrderAggregator> stepManager,
            String idempotencyKey
    ) throws RetryableExecutorException, NonRetryableExecutorException {

        // TODO: execute payment process here
        Thread.sleep(new Random().nextLong(1000, 3000));
        {
            //updates the aggregator with the payment id
            currentAggregator.setPaymentId("payment-1");
            currentAggregator.setPaid(true);
        }
        return stepManager.next(StockUpdateExecutor.class, () -> "MADE_PAYMENT");
    }

    @Override
    public SagaExecutionEventName doRevert(NonRetryableExecutorException processException,
                                           PlaceOrderAggregator finalAggregatorState,
                                           RevertHintStore revertHintStore,
                                           String idempotencyKey
    ) throws RetryableExecutorException {
        // TODO: execute payment revert process here
        return () -> "PAYMENT_REFUNDED";
    }
}
----

[[StockUpdateExecutor]]
==== StockUpdateExecutor

[source,java]
----
package demo.quickdemo.executors;

import demo.quickdemo.aggregators.PlaceOrderAggregator;
import lombok.SneakyThrows;
import org.stacksaga.ProcessStepManager;
import org.stacksaga.ProcessStepManagerUtil;
import org.stacksaga.RevertHintStore;
import org.stacksaga.annotation.SagaExecutor;
import org.stacksaga.core.SagaExecutionEventName;
import org.stacksaga.exception.RetryableExecutorException;
import org.stacksaga.exception.execution.NonRetryableExecutorException;
import org.stacksaga.executor.CommandExecutor;

import java.util.Random;

@SagaExecutor(
        executeFor = "stock-service",
        value = "StockUpdateExecutor"
)
public class StockUpdateExecutor implements CommandExecutor<PlaceOrderAggregator> {

    @SneakyThrows
    @Override
    public ProcessStepManager<PlaceOrderAggregator> doProcess(
            PlaceOrderAggregator currentAggregator,
            ProcessStepManagerUtil<PlaceOrderAggregator> stepManager,
            String idempotencyKey
    ) throws RetryableExecutorException, NonRetryableExecutorException {

        // TODO: execute stock update process here
        Thread.sleep(new Random().nextLong(1000, 3000));
        return stepManager.complete(() -> "STOCK_UPDATED");
    }

    @Override
    public SagaExecutionEventName doRevert(NonRetryableExecutorException processException,
                                           PlaceOrderAggregator finalAggregatorState,
                                           RevertHintStore revertHintStore,
                                           String idempotencyKey
    ) throws RetryableExecutorException {

        // TODO: execute stock revert process here
        return () -> "STOCK_REVERTED";
    }
}
----

[[creating_the_endpoint]]
=== Creating the endpoint
