= StackSaga Comprehensive Demo

:keywords: SatckSaga Spring microservice,spring boot saga,spring cloud microservice saga, saga design pattern,saga orchestration spring boot
:description: StackSaga Quick Start With Kubernetes

== Overview

In this demo, we're going to use StackSaga for the orchestrator service called `order-service` and see how the StackSaga works in detail like exception handling transaction retrying etc.

> IF you are new to StackSaga, it is recommended to read the xref:architecture:aggregator.adoc[architecture] and xref:framework:create-aggregator.adoc[reference documentation]
for reading individual components.

In this example, we have 4 utility microservices called `order-service`, `user-service`, `payment-service`, and `stock-service.` in addition to that,
https://spring.io/projects/spring-cloud-gateway[Spring Cloud Api Gateway] is used as the proxy server and as well as the Application Load Balancer (ALB).
And also Eureka Discovery is used for service registry.

The use-case is that the client can place an order, and then the order request should be completed go through these 4 services.

Each services' responsibilities as follows.

[horizontal]
`*order-service*`:: Order service is responsible for accepting the place order request and managing the entire transaction as the xref:architecture:saga-architecture.adoc#saga_orchestration_pattern[orchestrator].
And also it as a utility service, the service is responsible for storing the order related specific data in the order-service database.
According to this use-case, This is the service that stacksaga is added. other services will act as just regular services due to they are not responsible for managing an entire workflow (The entire transaction).

`*user-service*`:: To make the place order, we want to have the user details like delivery address, phone number, etc.
`user-service` managing the user-related data, and it provides endpoints to fetch the user's data.

`*payment-service*`:: In the placing order process, the utility `payment-service` involves to two main tasks.
+
. *Pre-Auth*: To make the *Pre-Auth* before doing the real transaction and to check that the payment can be done or not.
. *Make-Payment*: To make the payment (Real transaction).
If all the steps are done smoothly finally, the reserved transaction should be made.
These endpoints are provided by the `payment-service`.

`*inventory-service*`:: After making the pre-auth process, the real stock should be updated to reduce the quantity.
`inventory-service` is responsible for providing endpoints to update the real stock and restore the update in case of compensation.

All the services that we are going to build as follows.

* API-cloud-gateway
* Eureka-service
* Utility services
** order-service
** user-service
** stock-service
** payment-service

Additionally, https://live.stacksaga.org/[Stacksaga Cloud-Window] is used for monitoring the transaction tracing details and reviewing any errors related to transactions.

> Source code is available on https://github.com/stacksaga/stacksaga-examples/tree/main/stacksaga-demo-default[Github].

*This guide is divided into three sections for your convenience.*

. xref:stacksaga-demo.adoc#implementation[Implementation]
+
Guides for implementing all java classes. (focus the StackSaga concepts)
. xref:stacksaga-demo.adoc#deployment[Deployment]
+
Guides for creating and connecting The API-gateway and eureka service with utility services with all the configurations.
. xref:stacksaga-demo.adoc#runnning_and_monitoring[Running And Monitoring]
+
Monitoring the transaction data via the StackSaga Cloud-Window by running all the applications together.

=== High-level Implementation Diagram.

Here you can see what we are going to build in High-level.

[[demo_diagram]]
image::stacksaga-example-stacksaga-eureka-spring-cloud-api-gateway-demo-hight-level.drawio.svg[alt="stacksaga example stacksaga eureka spring cloud api gateway microservice demo hight level."]

* In the diagram, StackSaga icons image:stack-saga-icon.svg[width=20] are shown which parts are interacted with StackSaga.

[[implementation]]
== Implementation

As the first step, we are going to create the Orchestrator Service.
According to the use-case, the Orchestrator is `order-service`.

NOTE: Even if there are 4 utility services are involved to make the place order process, we mainly focus the *order-service* only.
Because, Other services are traditional spring boot services, and there is nothing to discuss. +
You can download the full source code from https://github.com/stacksaga/stacksaga-examples/tree/main/stacksaga-demo-default[here].

TIP: Selecting a service as an Orchestrator service or not, depends on your requirement.
If you want to manage the work flows of a long-running transaction inside a service, then you can make it as an Orchestrator service by adding StackSaga.

=== Create Order-Service (Orchestrator Service)

====  Create the project with spring initializer

Go to the https://start.spring.io/[spring initializer] and create your project with the following Dependencies.

NOTE: StackSaga supports for spring-boot 3.X and above.

* `spring-boot-starter-web`
* `spring-cloud-starter-netflix-eureka-client`
* `spring-boot-starter-data-jpa`
* `mysql-connector-java`
* `spring-cloud-starter-loadbalancer`
* `lombok`

NOTE: Due to that we are using eureka for service registry, we can use `spring-cloud-starter-loadbalancer` for internal client side load balancing.
Due to we use just `RestTemplate` as the httpclient, we have to annotate by `+@LoadBalanced+` annotation. +
[ https://github.com/stacksaga/stacksaga-examples/blob/main/stacksaga-demo-default/order-service/src/main/java/org/example/config/RestTemplateConfig.java[RestTemplateConfig] ]

After creating your project, add the StackSaga dependencies in the dependencies section.

There are 3 dependencies to be added based on your application as per the stacksaga architecture to work as an Orchestrator service.

stacksaga-spring-boot-starter:: The core of the framework.
+
[source,xml,subs="+attributes"]
----
<dependency>
   <groupId>org.stacksaga</groupId>
   <artifactId>stacksaga-spring-boot-starter</artifactId>
   <version>${org.stacksaga.version}</version>
</dependency>
----

stacksaga-mysql-support:: `stacksaga-mysql-support` is used for mysql database support for the event-store. due to we are using mysql as the primary database of the service, it is recommended to add the relevant event-store support implementation as a best practice. it helps to reduce the extra resources allocations and reduce the latency. because you are able to use the same physical database as an event-store with a different schema.
+
[source,xml,subs="+attributes"]
----
<dependency>
   <groupId>org.stacksaga</groupId>
   <artifactId>stacksaga-mysql-support</artifactId>
   <version>${org.stacksaga.version}</version>
</dependency>
----

stacksaga-connect-eureka-support:: due to the fact that we are in the eureka-based discovery environment, we need to use the `stacksaga-connect-eureka-support` dependency. it provides the instance related geographical (region, zone, instance ID, etc.) data to the SEC. it requires keeping the transactions in the event-store separately for in case of retrying with the help of xref:architecture:transaction-retrying.adoc#stacksaga_agent[stacksaga-agent].
+
[source,xml]
----
<dependency>
    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-connect-eureka-support</artifactId>
    <version>${org.stacksaga.version}</version>
</dependency>
----

Finally, the `pom.xml` file of the order-service will be like below.

.https://github.com/stacksaga/stacksaga-examples/blob/main/stacksaga-demo-for-kubernetes/order-service/pom.xml[icon:github[role=black,size=2x]]
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.example</groupId>
    <artifactId>order-service</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
    </properties>

    <dependencies>

        ...
        ...
        <!--Other dependencies-->

        <!--StackSaga related dependencies -->
        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-spring-boot-starter</artifactId>
            <version>${org.stacksaga.version}</version>
        </dependency>

        <dependency>
           <groupId>org.stacksaga</groupId>
           <artifactId>stacksaga-mysql-support</artifactId>
           <version>${org.stacksaga.version}</version>
        </dependency>

        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-connect-eureka-support</artifactId>
            <version>${org.stacksaga.version}</version>
        </dependency>

    </dependencies>
</project>
----

NOTE: Updating the configuration files related stuff will be discussed at the xref:stacksaga-demo.adoc#deployment[Deployment] section.

include::order-service-summary.adoc[]

include::creating-aggregator.adoc[]

include::creating-stacksaga-handler-class.adoc[]

include::creating-controller.adoc[]

include::creating-event-names-enum.adoc[]

include::creating-UserDetailExecutor.adoc[]

include::creating-OrderInitializeExecutor.adoc[]

include::creating-PreAuthExecutor.adoc[]

include::creating-StockUpdateExecutor.adoc[]

include::creating-MakePaymentExecutor.adoc[]

include::order-service-configuration-file.adoc[]

include::creating-api-cloud-gateway.adoc[]

include::creating-eureka-service.adoc[]

include::creating-user-service.adoc[]

include::creating-payment-service.adoc[]

include::creating-stock-service.adoc[]

include::application-deployment.adoc[]

include::application-testing.adoc[]


