= StackSaga With Kubernetes Example
:keywords: SatckSaga Spring microservice,spring boot saga,spring cloud microservice saga, saga design pattern,saga orchestration spring boot
:description: StackSaga Quick Start With Kubernetes

== Overview

This example will demonstrate how you can configure and work together StackSaga cloud ecosystem with Kubernetes environment by using inbuilt internal Kubernetes service communication (Without any spring related Discovery client implementation).

There are 3 utility service in the cluster called `order-service,` `user-service` and `stock-service.` as well as https://spring.io/projects/spring-cloud-gateway[Spring Cloud Api Gateway] is used as the (In K8s it is can be called ingress service) Application Load Balancer (ALB) and as well as the Reverse proxy server.
The `order-service` act as the StackSaga xref://[orchestrator service here]. as mentioned above, Eureka or any of Discovery client is not used for Service-Discovery and Service-Registry. to overcome the capability of Service-Discovery it is used inbuilt https://kubernetes.io/docs/concepts/services-networking/service/[Kubernetes Service].

image::stacksaga-example-drawing-stacksaga-kubernetes-spring-cloud-api-gateway-demo-hight-level.drawio.svg[alt="stacksaga example drawing stacksaga kubernetes spring cloud api gateway demo high-level architecture diagram"]
