= StackSaga Demo (Core concept practice)
:keywords: SatckSaga Spring microservice,spring boot saga,spring cloud microservice saga, saga design pattern,saga orchestration spring boot
:description: StackSaga Quick Start With Kubernetes

== Overview

In this demo, we are focusing on how to implement the StackSaga things in the spring boot in microservice architecture.

> IF you are new to StackSaga, it is recommitted to read the xref:architecture:aggregator.adoc[architecture] and xref:framework:create-aggregator.adoc[reference documentation]
for read individual components.

In this example, we have 4 utility microservices called `order-service`, `user-service`, `payment-service`, and `stock-service.` in addition to that,
https://spring.io/projects/spring-cloud-gateway[Spring Cloud Api Gateway] is used as the proxy server and as well as the Application Load Balancer (ALB).
and also Eureka Discovery is used for service registry.

The use-case is the clients can palace an order and then the order request should be completed go through these 4 services.

Each services' responsibilities as follows.

[horizontal]
`*order-service*`:: Order service is responsible for accepting the place order request and managing the entire transaction as the xref://[orchestrator].
and also as a utility service, the service is responsible for storing the order related specific data in the order-service database.
According to this us-case, This is the service that stacksaga is added.

`*user-service*`:: To make the process we want to have the user details like delivery address.
`user-service` managing the user-related data, and it provides endpoints to fetch the user's data.

`*payment-service*`:: In the placing order process, the utility `payment-service` involves to two main tasks.
+
. To make the *Pre-Auth* before doing the real transaction and to check that the payment can be done or not.
. To make the payment (Real transaction).
All the steps are done smoothly finally the reserved transaction should be made.
These endpoints are provided by the `payment-service`.

`*stock-service*`:: After making the pre-auth process, we should update the real stock.
`stock-service` is responsible for providing endpoints to update the real stock and restore the update.


All the services that we are going to build.

* api-cloud-gateway
* eureka-service
* utility servers
** order-service
** user-service
** stock-service
** payment-service

Additionally `stacksaga-admin-dashboard` is run monitoring the transactions.

> source code is available on //[Github].

This guide is divided into 3 sections for your convenience.

[1] xref:stacksaga-demo.adoc#implementation[Implementation]:: Guides for implementing all java classes. (focus the StackSaga concepts)
[2] xref:stacksaga-demo.adoc#deployment[Deployment]:: Guides for creating and connecting The API-gateway and eureka service with utility services with all the configurations.
[3] xref:stacksaga-demo.adoc#testing[Testing]:: Testing the application by running all the applications together.

=== High-level Implementation Diagram.

Here you can see what we are going to build in High-level.

image::stacksaga-example-stacksaga-eureka-spring-cloud-api-gateway-demo-hight-level.drawio.svg[alt="stacksaga example stacksaga eureka spring cloud api gateway microservice demo hight level."]

* In the diagram, StackSaga icons image:stack-saga-icon.svg[width=20] are shown which parts StackSaga interact.
* Red lines are shown how the StackSaga Admin interacts with the process and the request-flow.
* Black lines are shown how the regular http requests are done.

[[implementation]]
== Implementation

As the first step, we are going to create the Orchestrator Service called `order-service`.

NOTE: Even if there are 4 utility services in the diagram, we mainly focus the order service only.
Other services are traditional spring boot services, and there is nothing to discuss. +
You can download the full source code from //here.

=== Create Order-Service (Orchestrator Service)

The `order-service` is little bit spacial than the other utility servers because the `order-service` is the responsible for managing the entire transaction here.
That's why it called as xref://[Orchestrator Service].
And the next reason is that StackSaga involves that kind of service in your entire system.
Selecting a service as an Orchestrator service or not depends on your rearmament.

====  Create order the project with spring initializer

Go to the https://start.spring.io/[spring initializer] and create your project with the following Dependencies.

* `spring-boot-starter-web`
* `spring-cloud-starter-netflix-eureka-client`
* `spring-boot-starter-data-jpa`
* `mysql-connector-java`
* `lombok`

NOTE: In general, you would add `spring-eureka-client` but in this example eureka is not used.

After creating your project, add the StackSaga dependencies in the dependencies section.
There are 3 dependencies to be added based on your implementation.

* You can add the `stacksaga-spring-boot-starter` dependency based on the spring version that you wish to use.
#In this example, we will be using spring2.X.#
Spring 2.X::
+
[source,xml]
----
<dependency>
  <groupId>org.stacksaga</groupId>
  <artifactId>stacksaga-spring-boot-2-starter</artifactId>
  <version>1.0.0</version>
</dependency>
----
Spring 3.X::
+
[source,xml]
----
<dependency>
  <groupId>org.stacksaga</groupId>
  <artifactId>stacksaga-spring-boot-2-starter</artifactId>
  <version>1.0.0</version>
</dependency>
----

* Due to the database has been selected as Mysql, you have to add `stacksaga-mysql-support` dependency.
+
[source,xml]
----
<dependency>
    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-mysql-support</artifactId>
    <version>1.0.0</version>
</dependency>
----

* Due to we are going to Eureka as the discovery service, you have to add `stacksaga-connect-k8s-support` dependency.
+
[source,xml]
----
<dependency>
    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-connect-eureka-support</artifactId>
    <version>1.0.0</version>
</dependency>
----

Finally, the `pom.xml` file will be like below.

.https://github.com/stacksaga/stacksaga-examples/blob/main/stacksaga-demo-for-kubernetes/order-service/pom.xml[icon:github[role=black,size=2x]] pom.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.example</groupId>
    <artifactId>order-service</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
    </properties>

    <dependencies>

        ...
        ...
        <!--othe dependencies-->

        <!--StackSaga related dependacies -->
        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-spring-boot-2-starter</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-mysql-support</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-connect-eureka-support</artifactId>
            <version>1.0.0</version>
        </dependency>

    </dependencies>
</project>
----

NOTE: Updating the configuration files related stuff will be discussed at the xref:stacksaga-demo.adoc#deployment[Deployment] section.

include::order-service-summary.adoc[]

include::creating-aggregator.adoc[]


include::creating-controller.adoc[]

include::creating-OrderInitializeExecutor.adoc[]

include::creating-UserDetailExecutor.adoc[]

include::creating-PreAuthExecutor.adoc[]

include::creating-StockUpdateExecutor.adoc[]

include::creating-MakePaymentExecutor.adoc[]

[[deployment]]
== Deployment

=== Updating Configuration Properties

We have all 4 utility services and also other 2 services called api-gateway and eureka service to configure.
But except the order-service and api-gateway, other services are regular spring-cloud services.
Therefore, we are not going to deep diving to them.
You can see get the Configuration Properties through these links.

.Configuration Properties for regular services.
* xref://[user-service]
* xref://[stock-service]
* xref://[payment-service]
* xref://[eureka-service]

NOTE: The above links are related to the default deployment approach.
If you want
to see
how the applications are deployed
by using xref://[docker-compose] or xref:quick-examples:migrating-to-k8s.adoc[kubernetes],
reach these links.

Let's see how to configure The most important service called order-service.

[source,yaml]
.application.yaml
----
services:
  # <1>
  payment-service: http://payment-service
  stock-service: http://stock-service
  user-service: http://user-service
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      # <2>
      defaultZone: http://localhost:8085/eureka/
  instance:
    hostname: localhost
    # <3>
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  application:
    # <4>
    name: order-service
  datasource:
    username: root
    password: mafei
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stacksaga_place_order_demo_order_service?createDatabaseIfNotExist=true
  liquibase:
    # <5>
    enabled: false
# <6>
stacksaga:
  enable: true # <7>
  component-scan: org.example.aggregator # <8>
  app-release-version: 1.0.0 # <9>
  connect:
    admin-urls:
      - http://localhost:4444 # <10>
    admin-username: order-service-application-user # <11>
    admin-password: ykLO89Irx2Q6Cf2j # <11>
  datasource:
    # <12>
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/order-service?createDatabaseIfNotExist=true
      username: root
      password: mafei
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    author: mafei
    name: ${spring.application.name}
    version: ${stacksaga.app-release-version}
logging:
  level:
    org:
      stacksaga: debug
----

*Highlights*

<1> We decided to obtain the service's hosts that we use inside the order service from the configuration file.
Because the host nam will be different with other environments, (Direness profiles) like xref:stackSaga-demo-with-docker-and-docker-compose.adoc[docker-compose] and xref:migrating-to-k8s.adoc[kubernetes].
<2> Due to we use xref://[Eureka service discovery], we have provided the URL of the eureka server.

<3> To identify the eureka client (the instance,) you have to provide a unique id for each instance.

<4> it is most important because the service-user account should be equal the `spring.application.name`.

<5> `spring.liquibase.enabled` Even if you haven't added `liquibase` in your application, StackSaga uses  `liquibase` internally.
Due to the `liquibase` dependency exists in the application spring tries to access the autoconfiguration.
Then you will get an error.
To avoid that exception, you have to disable it.
+
WARNING: If you want to use `liquibase` in your application you are free to use as usual, and then you don't want to disable `liquibase` like above.

<6> The section that StackSaga configurations started.

<7> It is not enough to add the StackSaga dependencies.
To enable StackSaga, you have to enable StackSaga.

<8> We have to provide the packages to StackSaga where the `Aggregator` class are stored.
In our example the package is `org.example.aggregator`.
If you have multiple locations, you can provide a list of packages.

<9> This will be helpful to identify the metadata from the admin dashboard.
Because all the aggregator and executors metadata is saved under the `app-release-version`.
As an example, if you want to see what are the aggregators and executors that have been configured, you select the version and see them.

<10> The admin URL that the admin-server is running on.
If multiple xref://[admin-server] instances are running, you can provide all the list of URLs.

<11> The username and the password of the xref:admin:create_service_user.adoc[service-user] that you created for this `order-service`.

<12> You have to provide the datasource for the event-store that you use.
In this example we have used `stacksaga-mysql-support` dependency we have to provide the Mysql datasource configurations.

[[testing]]
== Testing

