= Stack Saga Demo With Docker And Docker Compose
:keywords: SatckSaga microservice,spring boot saga,spring cloud microservice saga, saga design pattern,saga orchestration spring boot
:description: Spring boot StackSaga Quick Start demo

[#Overview]
== Overview

This quick demo will guide you to build a StackSaga based microservice application with minimal requirements.

*Use case:* __A customer place an order and the order request comes to the spring api-gateway and it foreword the request to one of the down stream services called `order-service`.
The order service acts as the orchestrator service, and it handles the request by invoking other utility microservice services like  `user-service` , `order-service` , `stock-service` and so on with help of StackSaga.

__

The following steps are followed to overcome the quick start.

. Set up the StackSaga Admin server in the local environment and create a user for the orchestrator service (`order-service`).
. Initialize the `user-service` , `order-service` and `stock-service`.
And add the StackSaga dependencies to the orchestrator service (`order-service`).
. Create Aggregator and Executors.
. Final Teasing.

=== Set up the StackSaga Admin server in the local environment.

// todo download page should be linked
You can set up the StackSaga Admin server In different ways as Standalone Jar or Docker Image.

In this quick example Standalone Jar is used. go to the download page and download the latest version.
