= Saga Aggregator.

An *aggregator* is the main location that all the data should be kept for the entire transaction.
According to the StackSaga example, the entire process has set pf sub processes.
Create order, check user activeness, make payment, increase points and dispatch the order.
While those processes, you have to keep some data regarding the transaction.
For instance, the process is started from creating order.
After creating the order, you have a data to be kept.
As a response, you will get the order id.
You have to keep it, and you have to reuse it in your whole process.
After creating the order, you check the user activeness.
Then the user service is called and get the response of user's activeness and keep that data as user is active at the time of the process started.
Likewise, each and every process will return you to data.
Those data you have to keep in one location.
That location called as the aggregator.
At the start, you have to declare the variables, and after doing each process, you can update the values in the aggregator.
On the other hand, we can say it is the data bucket that you bring the data to each executor.

Another special thing is that the aggregator is used as the key of your entire transaction.
That means the executors are identified by the aggregator class that you use.
Because your entire transaction can have only one aggregator.
Therefore, the aggregator class is used in each and every time by representing the transaction.
For instance, according to the StackSaga example, the place order is the entire process.
It contains many sub processes like create order, check user ect.
Each process is introduced to the framework by using executors.
So, for each process have separate executors.
When you create each executor, you should mention what ks the aggregator that you want to use in that executor.

NOTE: You can store/update the data in the aggregator by using the process execution only (doProcess()).
If you want to keep some metadata while your revert/compensation processes, you can use the hint-store that the framework provides.

