= Aggregator Versioning

In StackSaga, versioning is the most important thing for you as the developer.
All the applications are being updated with new versions ever.
In StackSaga, you have to manage your versioning for each aggregator.
Because any kind of changes that you make regarding the aggregator, it caused for a version update.
Not only the aggregators, even if you make some changes in one of the executors, It also causes a version update.
Because every change you make related to the aggregator, it will change the aggregator state.
If the aggregator-state is changed, the version must be updated.

As an example, if you have PlaceOrderAggregator, the following changes can be caused to a version update.

*Old Aggregator version Structure.*

image:stacksaga-old-aggregator.drawio.svg[Stacksaga Old Aggregator Version,500]

*New Changes For Existing Aggregator Structure.*

. *Making changes in aggregator's class.*
+
image:stacksaga-aggregator-change.drawio.svg[Stacksaga Making Aggregator Changes,width=100%,opts=interactive,scaledwidth=100%]

+
- Compared to the old version, some changes have been made for the aggregator without doing any changes on the executors.
This will cause a version update.
<<aggregator_oriented_casting_architecture,See more>>
. *Adding new or removing existing executors* (<<query_executor_architecture,Query-Executor>>, <<command_executor,Command-Executor>>, or <<revert_after_executor,Revert-Executor>>)
+

image:stacksaga-executor-change.drawio.svg[Stacksaga Updating Executors,width=100%,opts=interactive,scaledwidth=100%]
+
- Compared to the old version, One Revert-Executor has been removed, and one Query-Executor and another Revert-Executor has been added as new executors.
This will cause a version update. <<executor_oriented_casting_architecture,See more>>
. *Making changes in the existing executors' classes.*
+

image:stacksaga-executor-class-change.drawio.svg[Stacksaga Making Executors Changes,width=100%,opts=interactive,scaledwidth=100%]
+
- Compared to the old version, Some changes have been made for some existing executors without changing any executors.
This will cause a version update.
