[[classification_of_saga_transactions]]
== Classification of SAGA transactions

According to the behaviors of the transaction, we can mainly identify 3 transaction types that can be happened when we use saga.

* *Fully success transaction*
* *Rollback/Compensation/Revert success transaction*
* *Rollback/Compensation/Revert failed transaction*


[[fully_success_transaction]]
=== icon:circle[role=green,1x] Fully Success

image:stacksaga-diagram-fully-successfull-transaction.drawio.svg[alt="stacksaga diagram fully successfull transaction"]

As we discussed earlier, we had used a number of microservices for executing one single execution.
Just assume we have used 5 microservices to execute the entire transaction,
and all of them have been executed successfully without any errors.
Therefore, no compensating executions as well.
All the primary executions are successful)


[[revert_success_transaction]]
=== icon:circle[role=yellow,1x] Compensation Success

image:stacksaga-diagram-revert-successfull-transaction.drawio.svg[alt="stacksaga diagram revert successfull transaction"]

In this time, An exception has occurred when one of microservices get execute.
Just assume the coordinator has been executed 3 microservices successfully, but at the 4th one, an error has occurred due to a network exception or whatever internal exception that the microservices have been thrown.
Now the coordinator has to execute revert function regarding all microservices that executed earlier.
So the coordinator will start to execute all the revert functions one by one as a sequence.
If those revert functions have been executed successfully, these kinds of transactions are going to these types.
Simply we did a set of transactions but unfortunately got an error, but all the revert processes are done successfully.

'''

[[revert_failed_transaction]]
=== icon:circle[role=red,1x] Compensation Failed

image:stacksaga-diagram-revert-failed-transaction.drawio.svg[alt="stacksaga diagram revert failed transaction"]

In this time, the coordinator tries to execute the transactions one by one.
But while doing the execution, an error occurred after doing some executions, and the coordinator gets started to execute all the revert processes that regard to the microservices that previously executed.
But unfortunately, while doing the revert executions, an error gets occurred because of a network issues.
(Network issues means it can be happened because there is no endpoint in active at that time or kind of actual network problems)

'''

== SAGA translations — Summary

*Fully success transaction*

image:fully-success-transaction-summary.svg[alt="Fully Success Transaction Summary",height=300]

'''

*Rollback/Compensation/Revert success transaction*

image:revert-success-transaction-summary.svg[alt="Revert Success Transaction Summary",height=300]

'''

*Rollback/Compensation/Revert failed transaction*

image:revert-failed-transaction-summary.svg[alt="Revert Failed Transaction Summary",height=300]


