= Command Executor

In the command executor, you will have two methods to be implemented.
One for the process the transaction forward.
And another one for its compensation.
Now you know what you can do inside the doProcess.
Let's talk about the doRevert method.
This is the location that you can execute your compensation atomic transaction.
For here, you will have the final status of the aggregator.
What is the final status of the aggregator?
It means the aggregator will change on each and every executor's doProcess method.
Some values are added and some values can be changed.
Just think the aggregator was used for 10 sub processes.
But the target processes are 20.
But the process can't be executed further more due to the error that occurred at step number 10. That means old 9 steps (sub executions/ sub transactions) have been done successfully.
But 10 was failed.
The framework ignores the changes of the step number 10.
Because the atomic transaction is failed and updated data is not valid due to the failure.
Therefore, in the `*doRevert*` method, you will get the aggregator object that was before going to be executed at step number 10.
For instance, if you change the value of xyz variable as 2, but in the step number 9, the value of xyz is null.
Because you have set the value then.
Then step number 10 is failed.
So the final aggregator that you will be given is xyz = null.
In the revert method, you are not permitted to change the data.
Because it is the final status of the aggregator.
It should be immutable and all the revert methods should use the data to process the compensation.
Due to having the getters and setters, you can set the values and change the values by using the reference.
But the framework ignores those updates.
Another special thing is that the *`revert`* method doesn't have a return.
Because the framework knows the order of the revert executions, and you can't change the direction.

image:Architecture-Stacksaga-command-executor-with-revert-executors.drawio.svg[alt=" Stacksaga Executors",width=100%,opts=interactive,scaledwidth=100%]
