According to the framework, one aggregator can have multiple executors based on your use case.
When you update the version of the service, you might want to remove existing executors or add new executors based on the update that should be done.
If you are going to add more additional executors to the existing aggregator that is called as *executor-oriented upcasting*.
And the opposite of that, if you remove some existing executors from the aggregator, that form is called as *executor-oriented-down-casting*.
Adding more is not a problem when the old event executors at all.
Just think, for instance, the old aggregator had 3 executors and the new aggregator has 4 executors due to the additional one, which has been added.
And after deploying the new version, the old events are executed through the new version.
That execution is not conflicted because, all the necessary executors are in the new version.

NOTE: IF there is an executor down-cast scenario, This time is not just like Executor-oriented-down-casting because the old event should have all the expected executors to be executed as you plan that event should be executed upon the old version's use case.
But in the new version, if one or more executors do not exist, most of the time the execution can be crashed.
(In rare cases, it might not be affected upon your update) by the way, even though you want to use some executors for the previous version and for the new version that executor is not used, that kind of situation is called as executor-oriented down-casting changes.
To avoid conflict in this way, the framework provides a feature to skip the old executor from the latest version, and the old executor is retained only for the remaining old events as it's.

== up-casting

image::Architecture-Stacksaga-executor-oriented-version-up-casting.drawio.svg[alt="Architecture Stacksaga executor-oriented version up-casting",height=400]

