= Saga Executor

According to the saga design pattern, you have to separate your entire transaction in to small atomic transactions.
In general, each atomic execution can have two executions called *process execution* and *Compensating execution*.

. *Process Execution / Main Execution*
- The main execution that you want to archive the atomic transaction. +
 +
As an example, In your <<what_is_stacksaga,place order example>> you had multiple individual processes to overcome the entire transaction like checking use's validation, checking stock's availability, updating stock, making payment, dispatching the order.
Those executions that caused to start the atomic processes are called as *Process execution*. +
Those are going forward [icon:arrow-circle-right[1x,role=green]].

. *Compensating Execution / Revert Execution*
- Most of the *Main Executions* can have a revert process to undo the executions that were done before If you want to get state back of your changed data (Because you can't do rollback just like you do in the Monolithic application).
The executions that are used for the reverting the done-process before are called as *Compensating Executions*. +
 +
As an example, If the stock-updating process was done successfully but due to one of the next atomic executions' failures, the stock-updating execution should be restored (Undo the process or get the state back). +
If the main execution has a revert execution, Those are going backward [icon:arrow-circle-left[1x,role=green]].


NOTE: Even though most of the executions can have a Compensating Execution / Revert Execution, Sometimes it is not.
It is based on your nature of the execution.
It can be explained by the CRUD operations.
If your atomic execution cased to a database's state change, That kind of executions can have a revert execution to get the state back.  +
As an example, In the above example, *checking use's validation, checking stock's availability* executions have no revert executions.
Because that were only read operations. +

|===
|Process Execution |Has a Revert

|*C* - Create
|*YES*

|*R* - Read
|*NO*

|*U* - Update
|*YES*

|*D* - delete
|*YES*
|===

To hand over your set of atomic transactions regarding the entire transaction to the <<SEC,SEC>>, you have to identify whether the atomic transaction has a revert operation or not.
Because StackSaga framework does provide tow Codespace types for setting up each atomic execution.

According to the framework, those *Codespaces* are called as *Executors*.

. <<query_executor_architecture,Query executors>>
- If some atomic process has no Compensating (query execution), those kinds of processes are used in a query executor. +
— In *Query Executor* has only one <<query_executor,method>> for making the main process.
+
*Example*: If you want to check, the user is active at the time of the transaction happen, and you want to keep the user's activeness until the end of the transaction. +
 +
<<query_executor,Implementation>>|<<query_executor_architecture,Read More>>
. <<command_executor_architecture,Command executors>>
- If some atomic process has a Compensating (command execution), those kinds of processes are used in a command executor. +
— In *Command executor* has two <<command_executor,methods>> for making the main process and making the revert process.
+
*Example*: Think that you want to create an order and order process is done successfully.
But after the make-payment process is failed.
Then the Compensating process will be started.
Now you must have a Compensating against the creating order.
So create an order process is a command process, and it goes to a command executor. +
 +
<<command_executor,Implementation>> | <<command_executor_architecture,Read More>>

The below diagram shows the Executors types and what are the methods they have.
To see how you can implement these executors, <<saga_executors,read here>>.

image:stack-saga-e-store-example-executor-types-in-stacksaga.drawio.svg[alt="Stacksaga Executors",height=300]
