== icon:circle[role=green,1x] Fully Success [[fully_success_transaction_scenario]]

here, the SEC has successfully executed all the executors. therefore, there is no compensation/revert execution was invoked. this is the success scenario we wish.

image::Architecture-Stacksaga-fully-success-transaction-stacksaga.drawio.svg[alt="StackSaga High-level architecture",height=300]

* pass:[<span class="rounded-number">1</span>] As the first step the user makes the request and the *OrderController* catch the request.

* pass:[<span class="rounded-number">2</span>] After having the request, initialize the place order aggregator and set the start executor into the StackSaga.
(In this time you have the transaction uid which is created by framework.
The transaction uid is the unique id for identifying each transaction.
You can get it from your created Aggregator object.)

* pass:[<span class="rounded-number">3</span>] now the execution processes are handled by the SEC.
Before invoking the executor that you provided as the start-executor SEC saves the initial state of the aggregator in the event-tore.

* pass:[<span class="rounded-number">4</span>] SEC executes the start-executor** ([Command] CreateOrderExecutor)** that you provided. pass:[<span class="rounded-number">4.1</span>] due to the executing the process method by the SEC, the *InternalOrderService's* *createOrder()* method will be invoked. pass:[<span class="rounded-number">4.2</span>] after successfully invoking the method, SEC will store the state of the aggregator. pass:[<span class="rounded-number">4.3</span>] after saving the state in the event-store, SEC will execute the *onEachProcessPerformed* method of the handler class that you provided. pass:[<span class="rounded-number">4.4</span>] then you can put your execution here to update the status of the place-order transaction. as the diagram, we have executed *updateCustomerOrderStatus()* method of *InternalOrderService* to update the status. pass:[<span class="rounded-number">4.5</span>] after updating the status of the place-order, you can notify your customer by sending the email or SMS or whatever method about the status of the order.

* pass:[<span class="rounded-number">5</span>] SEC executes the 2nd executor that you provided from the 1st executor. pass:[<span class="rounded-number">5.1</span>] due to the executing the *doProcess* method of the *[Query] UserExecutor* by the SEC, the *ExternalUserStatusService's* *checkUser()* method will be invoked.
pass:[<span class="rounded-number">5.2</span>] the *ExternalUserStatusService* will call the *user-service* and make a request.
pass:[<Span class="rounded-number">5.3</span>] after successfully invoking the request, SEC will store the state of the aggregator of 2nd process. pass:[<Span class="rounded-number">5.4</span>] after saving the state in the event-store, SEC will execute the *onEachProcessPerformed* method of the handler class that you provided.
+
#Due to this executor is a query executor, there is no status update process has been executed here.#
* pass:[<span class="rounded-number">6</span>] SEC executes the *[Command] PaymentExecutor* executor that you provided. pass:[<span class="rounded-number">6.1</span>] due to the executing the process method by the SEC, the *ExternalPaymentService's* *makePayment()* method will be invoked. pass:[<span class="rounded-number">6.2</span>] the *ExternalPaymentService* will call the *payment-service* and make a request to make-payment process. pass:[<span class="rounded-number">6.3</span>] after successfully making the request, SEC will store the state of the aggregator. pass:[<span class="rounded-number">6.4</span>] after saving the state in the event-store, SEC will execute the *onEachProcessPerformed* method of the handler class that you provided. pass:[<span class="rounded-number">6.5</span>] then you can put your execution here to update the status of the place-order transaction. as the diagram, we have executed *updateCustomerOrderStatus()* method of *InternalOrderService* to update the status. pass:[<span class="rounded-number">6.6</span>] after updating the status of the place-order, you can notify your customer by sending the email or SMS or whatever method about the status of the order.

* pass:[<span class="rounded-number">7</span>] SEC executes the *[Command] DeliveryExecutor* that you provided. pass:[<span class="rounded-number">7.1</span>] due to the executing the process method by the SEC, the *ExternalDeliveryService's* *addToDelivery()* method will be invoked. pass:[<span class="rounded-number">7.2</span>] the *ExternalDeliveryService* will call the *delivery-service* and make a request to add-to-delivery process. pass:[<span class="rounded-number">7.3</span>] after successfully making the request, SEC will store the state of the aggregator. pass:[<span class="rounded-number">7.4</span>] after saving the state in the event-store, SEC will execute the *onEachProcessPerformed* method of the handler class that you provided. pass:[<span class="rounded-number">7.5</span>] then you can put your execution here to update the status of the place-order transaction. as the diagram, we have executed *updateCustomerOrderStatus()* method of *InternalOrderService* to update the status. pass:[<span class="rounded-number">7.6</span>] after updating the status of the place-order, you can notify your customer by sending the email or SMS or whatever method about the status of the order.
* pass:[<span class="rounded-number">8</span>] as the final step the SEC will invoke the *onTransactionCompleted* method of the handler. pass:[<span class="rounded-number">8.1</span>] you can update the place-order status as the final state as *success*. pass:[<span class="rounded-number">8.2</span>] after updating the place-order status, you can notify it to the customer.
