== StackSaga in High-level

In the <<what_is_stacksaga,introduction section>>, We got a clear idea of how microservice architecture works, and what are the challenges that we have to face when implementing the microservice in traditional way.

Here, we are going to see how the StackSaga works together with typical microservice architecture.
It shows how StackSaga does impact on the default https://spring.io/microservices[spring boot microservice architecture].

For your convenience, both *Spring Microservice Architecture* and **Spring Microservice Architecture With StackSaga** diagrams have been added here.

=== *Spring Microservice Architecture* [[spring_microservice_architecture]]

image:microservice-high-level-diagram.svg[StackSaga High-level architecture,700]

=== **Spring Microservice Architecture With StackSaga**

image:stack-saga-high-level-diagram.svg[alt="StackSaga High-level architecture",700]

After adding stack saga in the microservice architecture, you can see there are some additional components in the high-level architecture diagram.

TIP: In the diagram, the *Gray* color components and lines are related to the typical microservice architecture, and additional stacksaga related components and lines have been colored by *Green* color.

Let's have a look at all the components and how they are interacted with each other.

. At first glance, you can see a major difference in database architecture.
// todo add links
The reason is StackSaga *SEC* uses *event sourcing* for managing your *aggregator state* for each *executor*.
In brief, StackSaga internally uses a database to string your execution data as events.
Therefore, If you are using StackSaga, you have to provide a database as the *event-store*.
+
TIP: Even though the diagram shows event-store per service, It can be configured as a single event-store for all services if the application is currently not a large one. *Read more*.
+
TIP: It is recommended to use one of the StackSaga database implementations that is equal to the primary database of the particular service.
Because, you don't need to configure another separate database and complicate the architecture. +
As an example, If the order-service uses *MYSQL* databases as the *primary database*, you can use the `stacksaga-mysql-support` implementation for the event-store.

. Next, Let's have a look at *StackSaga Admin*.
// TODO: add a link [facilities]
Admin provides a lot of facilities in the framework.
Primarily feature is monitoring and tracking the transaction's flow and trace.
For monitoring your transactions, Admin should be able to retrieve the transaction data from each event-store.
Internally, StackSaga client provides and exposes the endpoints for that.

According to the high-level architecture diagram and the brief explanation, you can identify one application and 4 libraries are involved for StackSaga.

NOTE: No need to add StackSaga for all the services in the ecosystem.
It can be added freely only to the services that you want to use.
If There is no any complex business domain in some services, there is no point in adding StackSaga for that particular service and keep it as it is in the ecosystem.
* `StackSaga-Admin-Server` Can be run as a standalone server.

NOTE: StackSaga-Admin's Database is used only for saving the *User's-Credentials* and the *Terminated Transactions'* metadata.
##Other data that you can see in the StackSaga-Admin dashboard are obtained from each service's event-store endpoints.
##

We had a quit a simple idea over this high-level overview.
Let's dive in to the deeper step by step to have a better understanding.
