= Introduction to StackSaga

Stacksaga is a Saga Orchestration engine framework that built top of the spring boot framework.
Orchestration engine helps you to manage your work flows to execute the primary executions and also the compensating executions in a very handy way.
And also you can see here some of the major features that StackSaga provides.

* Saga Orchestration engine for managing primary and compensating work flows.
* Transaction Coordination
* Idempotency (Ensures that repeating the same operation multiple times has the same effect as performing it once, which is crucial for reliability.)
* Transactions Asynchronous-Retrying
* Event sourcing (State Management)
* Monitoring Distributed transaction tracing via the StackSaga xref:admin:stacksaga-cloud-window.adoc[Cloud-Window].
* Concurrency Control
* Managing the Dual consistency problem.
And many more…

StackSaga consists of four major components in high-level.

. *StackSaga Framework.* +
StackSaga Framework provides orchestration engine to manage the saga work flows to execute the primary executions, compensating executions, transaction reties, and so on.
Stacksaga framework consists of three major components (dependencies).
** stacksaga-core (stacksaga-starter) +
The core and common features that are required by Saga execution coordinator engine.
** stacksaga-database-support +
The event-store supportive implementation for the saga engine.
It can be chosen as needed based on the database which is used for the service.
If the service that used as orchestration engine is using mysql, then the stacksaga-database-support implementation should be `stacksaga-starter-mysql`.
** StackSaga Environment Support +
The *StackSaga-environment-support* implementation facilitates the management of instance metadata required for handling the geographical identification of instances by interacting with the environment like Eureka, Kubernetes and so on.
. *StackSaga Agent*
. *xref:admin:stacksaga-cloud-window.adoc[StackSaga Cloud-Window]*
+
StackSaga cloud-window provides the monitoring facilities of the transactions and manages the security.



== Why StackSaga?[[why_stacksaga_should_be_used]]

If you implement the Saga orchestration design pattern in your system, you have to manually manage the work flows.
It's quite difficult to manage manually.
And specially managing the compensating in correct order is more difficult.
And also you have to follow a way to store all the events safely for retrying the execution where the execution was stopped temporarily.
To understand the implementation, let's have a look at an example.

Just imagine an E-Commerce application, and it should place an order.
Even though this action is a single one from the clint perspective, if we are in microservices architecture, that single action consists of multiple sub operations like initialize the order, collecting user details, making pre-auth, updating stocks, making the real payment and so on.
Doing these sub operations in sequence order is quite easy at first glance.
But all the time these sub operations might not be executed smoothly.

- Sometimes an error can occur while executing the last process or after some executions are done.
Then, the compensating executions have to be executed in descending order (last-in, first-out (LIFO)).
- Sometimes an error can occur due to resources unavailable like connection issues or the target service is unavailable temporarily.
If there is this kind of situation in the Saga, it's not recommended the starting compensating process.
Because eventually, we will be able to execute the execution successfully after the resources are available.
Here you have to implement a schedule mechanism to check the resource availability.

- Even if you managed to handle all those challenges.
Sometimes you may have to face dual-consistency problems as well.

Likewise, a lot of challenges will be covered by Stacksaga.
As a developer, you only have to focus on the business case if you are using StackSaga on your system.
The Stacksaga will take care of all other saga things and many challenges.

////

== Quick Understanding [[quick_understanding_example]]

== How StackSaga framework helps to overcome this problem?

StackSaga provides a *Codes paces* (Those called as *Command Executor*, *Query Executor* to provide your atomic operations that you did same in the place-order transaction.
The only thing that you have to do is to provide the execution-process inside the *Codespaces* and notify the exception type whether it is retryable or not.
Then the StackSaga engine will invoke each atomic transaction until the entire transaction gets succeeded (revert success or full process success).

image::stack-saga-codespacess.drawio.svg[alt=" Stacksaga Executors",width=100%,height=100vh]

In the above diagram, you can see the Codespaces for each atomic transaction.
You already might have the code portion for making the requests to other services.
In StackSaga, you can call those methods inside the *Codespaces*.
Then StackSaga coordinator will invoke your code portion through the *Codespaces*.
StackSaga does not involve your request.
Therefore, you don't want to really on specific protocol, and you can use any protocol for making request.
At least the endpoints should not be within the same https://spring.io/microservices[spring cloud ecosystem].
The endpoints can be anything external or within the ecosystem.
The only thing that you want to do is make the request part of each atomic transaction and warp up with *Codespaces* (<<executor_architecture,executors>>).

*StackSaga orchestration engine follows these concepts behind the scenes.*

. Saga design pattern
. Event sourcing
. Eventual consistency.

////


include::high_level_architecture.adoc[]