= Key Steps of ecosystem in High-Level

To get started and implementing StackSaga in your environment, the following steps should be followed.

NOTE: All the steps have been implemented in the xref:quick-examples:stacksaga-demo.adoc[Comprehensive demonstration].

. Initialize the admin server with super admin.
- As the first step, you have to create initialize the admin server.
See the initialization steps.
+
[ xref:admin:stacksaga_admin.adoc[Concept] | xref:quick-examples:stacksaga-demo.adoc#set_up_stacksaga_admin_server_and_dashboard[Implementation] ]

. Register your orchestration service(s) with admin server.
- To register the orchestration services (The service that Stacksaga framework is added) in the admin server, the super admin or admin has to create a user for service with service privileges.
As a best-practice, the StackSaga team recommends you to create one user for one service group.
(A service group can have multiple instances, but the service names are the same.
For instance, order-service should have a service user called order-service-application-user.
And payment service should have a service user called payment-service-application-user.
At the start-up, the connector will verify your service credentials and let you the access to register and run the service.
+
[ xref:admin:stacksaga_admin.adoc#create_service_user[Concept] | xref:quick-examples:stacksaga-demo.adoc#set_up_stacksaga_admin_server_and_dashboard[Implementation] ]

. Create Aggregator.
. Create Executors.
. Execute a transaction.
- This is the main part that you are willing to see.
The request comes through the API gateway as usual, and the StackSaga coordinator will obtain the request data that you pass, and the coordinator will handle all the process and executions as you have guided the framework.
For this process only StackSaga coordinator was involved.
Read the implementation Or read how stack saga execution types work to see more, in detail.
. Monitor transactions execution data.
- To see the execution data, you should have to have a user account on the admin server.
If you are the super admin, the super admin can see all the details.
But as a best-practice, make sure to create a separate individual account for each user that wat to access the admin server to see the transaction data.
After login to the dashboard, you have to give the access path of the API gateway that you want to access the services.
You will be able to see the transaction data.