= Key Processes of ecosystem

To understand the relation of those components whole process can be summarised as follows.

. Initialize the admin server with super admin.
- As the first step, you have to create initialize the admin server.
See the initialization steps.
. Register API gateways with admin server
- To connect the StackSaga, your API gateway should provide an API-gateway-user credentials.
Therefore, super Admin should create a user with API gateway authorization (role).
After creating the API gateway user, the api gateway can be run because StackSaga Shield will check your credentials connecting with the admin server.
For this process, StackSaga server and StackSaga Shield were involved.
See the implementation to see more in detail.
. Register each microservice with admin server.
- To register the services in the admin server, the super admin or admin has to create a user for service with service privileges.
As a best-practice, the StackSaga team recommends you to create one user for one service group.
(A service group can have multiple instances, but the service names are the same.) For instance, order-service should have a service user called order-service-general-user.
And payment service should have a service user called payment-service-general-user.
At the start-up, the connector will verify your service credentials and let you the access to register and run the service.
For this process, StackSaga Server and StackSaga Connector were involved.
See the implementation to see more in detail.
. Execute a transaction.
- This is the main part that you are willing to see.
The request comes through the API gateway as usual, and the StackSaga coordinator will obtain the request data that you pass, and the coordinator will handle all the process and executions as you have guided the framework.
For this process only StackSaga coordinator was involved.
Read the implementation Or read how stack saga execution types work to see more, in detail.
. Monitor transactions execution data.
- To see the execution data, you should have to have a user account on the admin server.
If you are the super admin, the super admin can see all the details.
But as a best-practice, make sure to create a separate individual account for each user that wat to access the admin server to see the transaction data.
After login to the dashboard, you have to give the access path of the API gateway that you want to access the services.
You will be able to see the transaction data.

For this process, StackSaga server, StackSaga Shield and StackSaga Connector were involved.

