= Query Executor

In the query executor, you only have a one method to do your atomic execution.
It's called as atomic process execution.
Upon the aggregator that you provided you will have the aggregator as a parameter.
That is the aggregator object which runs for the entire transaction.
In the method, you are permitted to read write and update the values from that object.
And you can invoke your atomic execution inside the method body by using the values of given aggregator.
According to the StackSaga example, just think we are going to check the user status.
To do this part, you already have the service class and the function.
For here, the only thing that you do is introduction that method and get the relevant data from the given aggregator.
The framework is responsible for invoking that method you mentioned. ** In one executor, you can introduce one atomic process only.

Finally, you have to return what is the next executor that you want to execute.
It is totally runtime.
You can decide it the data by using the given aggregator or by anything else.
Or, if your process is completed from this execution, you can notify about that by complete single.


