[[revert_failed_transaction_scenario]]
= icon:circle[role=red,1x] Compensation Failed Transaction

image::Architecture-Stacksaga-evert-failed-transaction-scenario.drawio.svg[alt="Compensation/Revert failed transaction scenario",height=300]

IMPORTANT: Even though if there is a *Compensation Failed Transaction* for theoretically, Make sure that a revert exception doesn't occur in your production application.

TIP: *Can we ignore the Exceptions to execute the rest of revert executions?* +
The answer is yes.
You know that if an exception happens while reverting the entire transaction, the transaction is terminated from that point.
Then the next rest of revert executions that should be invoked are not executed. +
Sometimes that can have some revert-executions more important to be executed, and it is a must.
But if you have an error before executing that revert-execution, that important revert-execution is not executed. +
Most of the time, those exceptions will be that you didn't except. +
To avoid transaction-termination due to revert-error, you can catch all the exceptions and filter the exception that you know well and ignore another all rest of exceptions without throwing to the SEC.
[ xref:quick-examples:stacksaga-demo.adoc#tip_for_avoid_transaction_termination[See a real usage] ]



