= Introduction to Saga Design Pattern

[[what_is_saga_architecture_pattern]]
== What Is Saga Architecture Pattern?

The Saga architecture pattern provides transaction management using a sequence of local transactions.
A local transaction is the unit of work performed by a saga participant.
Every operation that is part of the Saga can be rolled back by a compensating transaction.
Further, the Saga pattern guarantees that either all operations are complete successfully or the corresponding compensation transactions are run to undo the work previously completed.
In the Saga pattern, a compensating transaction must be important and retryable.
These two principles ensure that a transaction can be managed without any manual intervention.
The Saga Execution Coordinator (SEC) ensures guarantees these principles:

image::compensating-transaction.svg[alt="distributed transaction saga, stacksaga",height=300]

The above diagram shows how to visualize the Saga pattern for the previously discussed online order processing scenario.

[[saga_orchestration_pattern]]
== Saga Orchestration Pattern

In the Orchestration pattern, a single orchestrator is responsible for managing the overall transaction status.
If any of the microservices encounters a failure, then the orchestrator is responsible for invoking the necessary compensating transactions.
The Saga orchestration pattern is useful for brownfield microservice application development architecture.
In other words, this pattern is suitable if we already have a set of microservices and would like to implement the Saga pattern in the application.
We need to define the appropriate compensating transactions to proceed with this pattern.

[[eventual_consistency]]
== Eventual Consistency

Eventual consistency is a technique that ensures data consistency and availability by asynchronous communication and ensuring that when an error occurs in a specific process, the error will be resolved eventually without having to roll back the whole process.

[[classification_of_saga_transactions]]
== Classification of SAGA transactions

According to the behaviors of the transaction, we can mainly identify 3 transaction types that can be happened when we use saga.

* *Fully success transaction*
* *Rollback/Compensation/Revert success transaction*
* *Rollback/Compensation/Revert failed transaction*


include::classification_of_saga_transactions.adoc[]