= Saga execution coordinator. (SEC) [[SEC]]

The Saga Execution Coordinator (SEC) is the core component for implementing a successful Saga flow.
It maintains a Saga log that contains the sequence of events of a particular flow.
If a failure occurs within any of the components, the SEC queries the logs and helps identify which components are impacted and in which sequence the compensating transactions must be executed.
Essentially, the SEC helps maintain an eventually consistent state of the overall process.

If the SEC component itself fails, it can read the SEC logs when coming back up to identify which of the components are successfully rolled back, identify which ones were pending, and start calling them in reverse chronological order.

* Stores & interpret a Saga’s state machine
* Executes the Requests of a Saga by talking to other services
* Handle failure recovery by executing Compensating Requests

image:stack-saga-e-store-example-SEC.drawio.svg[alt="StackSaga  Saga Execution Coordinator (SEC)",width=100%,opts=interactive,scaledwidth=100%]

NOTE: If you want to see how SEC works for each transaction mode in detail, please refer <<stack_saga_transaction_type,StackSaga Transaction Types>>.
It will give you a better understanding of StackSaga framework as well.
