= Aggregator Version Casting

All the applications will be updated by changing their versions from time to time.
When a new version is deployed, the old version will be replaced by the new version (if you are not going to use service-mesh).
But in the event-based architecture, some events can have been waiting to be executed when the new version is being deployed or after deployed as well.
Then the old event should be mapped with the previous version.
And if you don't consider the old version’s execution, when developing the new version, the events will be conflicted or crashed.
Because, the old version's event is going to be executed by using the new version of the same service.
But the new version doesn't allow the old events, and then the event will face for an exception due to that the event's data is not mapped with different versions to be executed smoothly.

. <<aggregator_oriented_casting_architecture,Aggregator-Oriented casting>>
... Aggregator upcast
... Aggregator downcast
. <<executor_oriented_casting_architecture,Executor-Oriented casting>>
... Executor upcast
... Executor downcast

include::aggregator_oriented_casting_architecture.adoc