= Introduction to StackSaga

Stacksaga is a Saga Orchestration engine framework that built top of the spring boot framework.
Orchestration engine helps you to manage your work flows to execute the primary executions and also the compensating executions in a very handy way.
And also you can see here some of the major features that StackSaga provides.

* Saga Orchestration engine for managing primary and compensating work flows.
* Transaction Coordination
* Idempotency (Ensures that repeating the same operation multiple times has the same effect as performing it once, which is crucial for reliability.)
* Retrying transactions
* Event sourcing (State Management)
* Monitoring Distributed transaction tracing via the StackSaga admin dashboard.
* Concurrency Control
* Managing the Dual consistency problem. and many more..

StackSaga consists of two major components in high-level.

. *StackSaga-Admin*
+
StackSaga admin mainly provides the monitoring facilities of the transactions and manages the security.
. *StackSaga Framework*.
- StackSaga Framework provides orchestration engine to manage your work flows to execute the primary executions and also the compensating executions.



== Why stackSaga should be used  [[why_stacksaga_should_be_used]]

If you implement the Saga orchestration design pattern in your system, you have to manually manage the work flows.
It's quite difficult to manage manually.
And specially managing the compensating in correct order is more difficult.
And also you have to follow a way to store all the events safely for retrying the execution where the execution was stopped temporarily.
To understand the implementation, let's have a look at an example.

Just imagine an E-Commerce application, and it should place an order.
Even though this action is a single one from the clint perspective, if we are in microservices architecture, that single action consists of multiple sub operations like initialize in the order, correcting user details, making pre-auth, updating stocks, making the real payment so on.
Doing these sub operations in sequence order is quite easy at first glance.
But all the time these sub operations might not be executed smoothly.

Sometimes an error can occur while executing the last process or after some executions are done.
Then you have to execute the compensating executions as the order of last-in first-out (LIFO).
Sometimes an error can occur due to resources unavailable like connection issues or the target service is unavailable temporarily.
If there is this kind of situation in the Saga, it's not recommended the starting compensating process.
Because eventually, we will be available to execute the execution successfully after the resources are available.
Here you have to implement a schedule mechanism to check the resource availability.
Even if you managed to handle all those challenges, Sometimes you may have to face dual-consistency problems as well.
Likewise, a lot of challenges will be covered by Stacksaga.

As a developer, you only have to focus on the business case.

The Stacksaga will take all other saga things and many challenges.

== Quick Understanding [[quick_understanding_example]]

Just imagine that you have a business domain for placing an order in microservice architecture.
So you can have multiple services, and you have to visit all over the services to complete the place-odder transaction.

The services might be as follows:

- Order-service
- Payment-service
- Cart-service
- Delivery-Service and many more.

IF you execute the place order process, you have to go through each and every service one by one after competing each of them.
There is no issue with that if the entire process is completed successfully all the time.
But in microservice architecture, it is not possible and there is a possibility to have an at least connection issue.
Just think all the past services are done successfully, but the last execution is failed due to insufficient balance or payment-service's failure.
Then you have to revert (Compensating-transaction) all the past executions *one by one as the same-order*
that those services were executed to overcome the eventual consistency according to the Saga design pattern.
It is very complicated if you are going to do manually.
Other than that, just imagine you are able to handle and bare the last failed execution, and you started to revert all the past executions one by one.
Just imagine very unfortunately, you are getting a connection error at the last revert process.

*Oops!*
Now your in a big trouble with your data consistency.
Because your both transaction Forward-process and Revert-process are failed at this moment.
You can do nothing in this kind of situation.

You were unable to reach the target end execution to forward.
Therefore, you stated revert-process for all the past executions one by one (Last-In, First-Out order [*LIFO*] ).
But unfortunately, You were unable to reach the target final revert as well due to a network issue.

Here you can see What happened to your place-order transaction with a diagram.

image:revert-failed-transaction-intro.svg[alt="StackSaga revert failed transaction",width=100%,opts=interactive,scaledwidth=100%]

. You Started the place-order transaction there.
. Stopped the place-order transaction due to not sufficient balance.
. Your target transaction ending for a successful transaction.
. Started revert process due the transaction was stopped unsuccessfully.
. The revert process was stopped due to a connection error.
. The target revert process ending for a successful revert transaction.

== How StackSaga framework helps to overcome this problem?

StackSaga provides a *Codes paces* (Those called as *Command Executor*, *Query Executor* to provide your atomic operations that you did same in the place-order transaction.
The only thing that you have to do is to provide the execution-process inside the *Codespaces* and notify the exception type whether it is retryable or not.
Then the StackSaga engine will invoke each atomic transaction until the entire transaction gets succeeded (revert success or full process success).

image::stack-saga-codespacess.drawio.svg[alt=" Stacksaga Executors",width=100%,height=100vh]

In the above diagram, you can see the Codespaces for each atomic transaction.
You already might have the code portion for making the requests to other services.
In StackSaga, you can call those methods inside the *Codespaces*.
Then StackSaga coordinator will invoke your code portion through the *Codespaces*.
StackSaga does not involve your request.
Therefore, you don't want to really on specific protocol, and you can use any protocol for making request.
At least the endpoints should not be within the same https://spring.io/microservices[spring cloud ecosystem].
The endpoints can be anything external or within the ecosystem.
The only thing that you want to do is make the request part of each atomic transaction and warp up with *Codespaces* (<<executor_architecture,executors>>).

*StackSaga orchestration engine follows these concepts behind the scenes.*

. Saga design pattern
. Event sourcing
. Eventual consistency.



