:impl_name: mysql
// SEC Metadata for SEO
:title: Stacksaga MySQL Reactive Support | MySQL Database Integration Guide [title]
:toc-title: Stacksaga Cassandra Reactive Support | Cassandra Database Integration Guide [toc-title]
:description: Learn how to integrate Stacksaga with MySQL using the reactive support module. Step-by-step guide for schema setup, connection configuration, and transaction retry in distributed systems.
:doctitle: Stacksaga MySQL Reactive Support [doctitle]
:revnumber: 1.0.0
:revdate: {localdate}
:keywords: Stacksaga, MySQL, Reactive Support, Database Integration, Event Store, Transaction Retry, Distributed Systems, Java, Orchestrator, Schema Creation, Connection Configuration, R2DBC, High Throughput, Idempotency, Saga design pattern, Spring Boot, Spring WebFlux, Spring Saga
:robots: index,follow

= Stacksaga Mysql Reactive Support

== Overview

`stacksaga-mysql-reactive-support` is the *mysql reactive(non-blocking)* implementation of the xref:stacksaga-database-support:overview/database-support-overview.adoc[].
it provides all the necessary facilities for accessing the mysql database for the Stacksaga engine. and also it provides the endpoints for accessing the event-store to see the tracing details from the xref:trace-window:stacksaga-trace-window.adoc[].

Here you can see where the `stacksaga-mysql-reactive-support` fits into the overall Stacksaga architecture.

image::mysql/stacksaga-diagram-stacksaga-components-database-support-mysql.svg[alt="stacksaga components overview with mysql database support",title="Stacksaga components overview with mysql database support"]

NOTE: read xref:stacksaga-database-support:overview/database-support-overview.adoc[] to have a better understanding of the database support modules like the responsibilities, architecture etc.

== Adding mysql support to your orchestrator application

adding mysql support to your orchestrator application consists of 3 simple steps.

xref:#adding-mysql-support[Step-1]:: Add `stacksaga-mysql-reactive-support` as a dependency to your orchestrator application.
xref:#executing-schema-creation-script[Step-2]:: Execute the shema creation script that is provided by the `stacksaga-mysql-reactive-support` module.
xref:#connection-configuration[Step-3]:: Configure the mysql connection configurations.

The following sections will explain each step in detail.

[[adding-mysql-support]]
=== Adding `stacksaga-mysql-reactive-support` as a dependency

Here is the way that you can add the library into your existing orchestrator application as a dependency.

.Adding `stacksaga-mysql-reactive-support` as a dependency
[source,xml]
----
<dependency>
    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-mysql-reactive-support</artifactId>
    <version>${org.stacksaga.version}</version>
    <exclusions>
        <!--<exclusion>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-mysql-api-servlet</artifactId>
        </exclusion>-->
        <exclusion>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-mysql-api-webflux</artifactId>
        </exclusion>
    </exclusions>
</dependency>
----

IMPORTANT: Make sure to exclude the `stacksaga-mysql-api-servlet` or `stacksaga-mysql-api-webflux` module based on your orchestrator application type (spring mvc or spring webflux).
because, stacksaga-database-support modules provide built-in API for both spring mvc and spring webflux applications. for example if you are using spring mvc, then you should exclude the `stacksaga-mysql-api-webflux` module. or if you are using spring webflux, then you should exclude the `stacksaga-mysql-api-servlet` module. in this example we are excluding the `stacksaga-mysql-api-webflux` module because we are assuming that the orchestrator application is a spring mvc application.

[[executing-schema-creation-script]]
=== Executing the schema creation script

Execute the following script in your mysql database to create the necessary tables and indexes that are required by the Stacksaga engine to save the transaction data.

Get the script from the following location on https://github.com/stacksaga/scripts/blob/main/database-support/stacksaga-mysql-support/schema.sql[GitHub].

IMPORTANT: Make sure to verify that the script is the latest version.

[[secondary-internal-service-for-transaction-retry]]
== Secondary Internal Service for Transaction Retry

include::stacksaga:stacksaga-database-support:secondary-internal-service-for-transaction-retry.adoc[leveloffset=+1]

[[connection-configuration]]
== Configuring mysql connection

By default `stacksaga-mysql-reactive-support` uses spring reactive `R2DBC` connection to connect to the mysql database.
because even if your orchestrator application is a spring mvc application, the Stacksaga engine internally uses reactive programming model to achieve better performance and scalability.
therefore if default `R2DBC` connection factory is not used in your application, you can configure the connection factory for the Stacksaga engine by providing the necessary properties in your application configuration file.
or, otherwise, you can provide a custom `io.r2dbc.spi.ConnectionFactory` can provide it as a bean of `org.stacksaga.mysql.reactive.provider.ConnectionFactoryProvider` like below.

make sure to update the `stacksaga.mysql.use-default-r2dbc-connection=false` property in your application configuration file to mention not use the default `r2dbc` connection factory by the stacksaga.

[source,java]
----
@Configuration
public class CustomConfig {
    @Bean
    public ConnectionFactoryProvider customConnectionFactory() {
        ConnectionFactoryOptions options = ConnectionFactoryOptions.parse("r2dbc:mysql://localhost:3306/order-service-event-store")
                .mutate()
                .option(ConnectionFactoryOptions.USER, "dbuser")
                .option(ConnectionFactoryOptions.PASSWORD, "dbpassword")
                .build();
        ConnectionPoolConfiguration configuration = ConnectionPoolConfiguration.builder(ConnectionFactories.get(options))
                .initialSize(5)
                .maxSize(20)
                .maxIdleTime(java.time.Duration.ofMinutes(30))
                .build();
        return () -> new ConnectionPool(configuration);
    }
}
----

this approach keeps your default connection factory intact, and the Stacksaga engine will use the custom connection factory that you have provided.

[[configuration-properties]]
== Configuration Properties

[.scrollable-div]
--

[cols="1,1,1,<1"]
[.properties-table]
|===
|Property Name|Default Value|Type|Description

4+| you can use the default spring `r2dbc` mysql connection properties that starts with `spring.r2dbc` prefix to configure the mysql connection for the stacksaga engine. otherwise, you can provide a custom one as mentioned xref:#connection-configuration[here].

|`stacksaga.mysql.transaction.retry.crashed-restore-retention-period-seconds` | `300` (five-minutes) | long | if the transaction has not been updated after configured duration, it is considered as the transaction was dismissed due to crash, or it may be in a queue in rare case. even if the transaction is in a queue, the transaction is restored for retrying by considering it has crashed.
the value should be provided in seconds.

|`stacksaga.mysql.transaction.retry.retention-period-seconds` | `60` (one-minute) | long | How long the transaction should be kept waiting to next expose the transaction for retrying.
This ensures that avoiding the transaction retrying frequently withing a short period of time. the transaction is frozen for some period of time, even the transaction failed again after retrying recently.

[[stacksaga-retry-server-configurations]]
|`stacksaga.retry.server.port` | `4455` | int | The secondary HTTP port used for internal transaction retry communication.
|`stacksaga.retry.server.max-threads` | `20` | int | Maximum number of threads for the retry service connector.
|`stacksaga.retry.server.min-spare-threads` | `4` | int | Minimum number of spare threads for the retry service connector.
|`stacksaga.retry.server.address` | `0.0.0.0` | string | The network address the retry service binds to.

|===

--
