:impl_name: mysql
:title: Stacksaga MySQL Reactive Support
:description: Learn how to integrate Stacksaga with MySQL using the reactive support module. Step-by-step guide for schema setup, connection configuration, and transaction retry in distributed systems.
:doctitle: Stacksaga MySQL Reactive Support
:revnumber: 1.0.0
:revdate: {localdate}
:keywords: Stacksaga, MySQL, Reactive Support, Database Integration, Event Store, Transaction Retry, Distributed Systems, Java, Orchestrator, Schema Creation, Connection Configuration, R2DBC, High Throughput, Idempotency, Saga design pattern, Spring Boot, Spring WebFlux, Spring Saga
:robots: index,follow

= Stacksaga Mysql Reactive Support

== Overview

`stacksaga-mysql-reactive-support` is the *mysql reactive(non-blocking)* implementation of the xref:stacksaga-database-support:overview/database-support-overview.adoc[].
it provides all the necessary facilities for accessing the mysql database for the Stacksaga engine. and also it provides the endpoints for accessing the event-store to see the tracing details from the xref:trace-window:stacksaga-trace-window.adoc[].

NOTE: read xref:stacksaga-database-support:overview/database-support-overview.adoc[] to have a better understanding of the database support modules like the responsibilities, architecture etc.

[[adding-mysql-support]]
=== Adding `stacksaga-mysql-reactive-support` as a dependency

Here is the way that you can add the library into your existing orchestrator application as a dependency.

.Adding `stacksaga-mysql-reactive-support` as a dependency
[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-bom</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
<dependency>
    <groupId>org.stacksaga</groupId>
    <artifactId>stacksaga-mysql-reactive-support</artifactId>
</dependency>
----

IMPORTANT: It is recommended to http://initializer.stacksaga.org/[StackSaga Initializer] to get the dependency snippets for your project for the StackSaga related dependencies, as it will ensure you have the correct versions and configurations for your project setup.

include::../sql-database-support/stacksaga-sql-configuration-properties.adoc[]
