= Migrate To Kubernetes Environment

To Migrate to the Kubernetes environment, we will be using the same place-order example by changing the required properties and dependencies.

* You can get the fully updated source code xref://[here].

> It is recommitted to read the xref:framework:create-aggregator.adoc[k8s reference documentation] to have a better understanding.

In the place-order example, we used Eureka-Service as the discovery server and service registry.
But in general, if are moving to the Kubernetes Environment, Kubernetes supports in-built service registry and service discovery features.

But know that Eureka-server cached registry was used for electing the leader for doing the retry and other StackSaga scheduling.
Then, if we don't use Eureka-server, how StackSaga selects the leader in the Kubernetes Environment?

StackSaga provides a dependency called `stacksaga-connect-k8s-support`
and it uses internally https://kubernetes.io/docs/concepts/architecture/leases/#leader-election[kubernetes lease leader election] for leader election.
xref:framework:stacksaga_in_kubernetes.adoc[Read more..]

So then you have to remove the `stacksaga-connect-eureka-support`
and add the `stacksaga-connect-k8s-support`.

Here is the updated `pom.xml` for `order-service`.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>org.example</groupId>
    <artifactId>order-service</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-cloud.version>2021.0.3</spring-cloud.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>


        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-spring-boot-starter</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-mysql-support</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!--removed stacksaga-connect-eureka-support-->
        <!--<dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-connect-eureka-support</artifactId>
            <version>1.0.0</version>
        </dependency>-->

        <!--added stacksaga-connect-k8s-support-->
        <dependency>
            <groupId>org.stacksaga</groupId>
            <artifactId>stacksaga-connect-k8s-support</artifactId>
            <version>1.0.0</version>
        </dependency>

    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
----

WARNING: Make sure to keep the `spring-cloud-dependencies` as it is in the `dependencyManagement` section.
Because `stacksaga-connect-k8s-support` uses it for managing the internal dependencies.

Now let's create a new profile and a configuration file for `k8s`.

TIP: https://docs.spring.io/spring-boot/docs/1.2.0.M1/reference/html/boot-features-external-config.html#boot-features-external-config-profile-specific-properties[Spring Profiles] provide a way to segregate parts of your application configuration and make it only available in certain environments.

[source,yaml]
----
services:
  payment-service: http://payment-service-service
  stock-service: http://stock-service-service
  user-service: http://user-service-service
server:
  port: 8080

spring:
  application:
    name: order-service

stacksaga:
  component-scan: org.example.aggregator
  app-release-version: 1.0.0
  cloud:
    k8s:
      namespace: default
      service-host: http://${spring.application.name}-service
      leader-election:
        lease-duration: 3m
        renew-deadline: 1m
        retry-period: 30s
  connect:
    admin-urls:
      - http://stacksaga-admin-server-service:4444
    admin-username: order-service-application-user
    admin-password: dtj8lEfssVUCsaHe
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/order-service?createDatabaseIfNotExist=true
      username: root
      password: mafei
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    author: mafei
    name: ${spring.application.name}
    version: ${stacksaga.app-release-version}
logging:
  level:
    org:
      stacksaga: trace
      springframework: debug
    root: info
----
