= Stacksaga Dependencies and Relations

image::implementations:overview/stacksaga-dependencies-and-relations.svg[]

The above diagram shows all the main dependencies that should be added to your project and their relations of the StackSaga umbrella project.

* As per the diagram, stacksaga has two main implementations called
** xref:implementations:stacksaga-sync/overview.adoc[stacksaga framework] (synchronous implementation)
** xref:implementations:stacksaga-kafka/overview.adoc[stacksaga-kafka framework] (asynchronous implementation using Kafka as the message broker)
* If you are using stacksaga framework(synchronous implementation), mainly you need to add the dependencies to the flowing services,
*** orchestrator-service +
In the orchestrator-service, you need to add three main dependencies as follows,
**** xref:stacksaga-sync/overview.adoc#stacksaga_components[stacksaga-spring-boot-starter]
**** xref:stacksaga-database-support:overview/database-support-overview.adoc[stacksaga-database-support] (you can choose any one of the database support modules as per your primary database)
**** xref:stacksaga-environment-support:overview/stacksaga-environment-support.adoc[stacksaga-environment-support] (you can choose any one of the environment support modules as per your deployment environment)
*** xref:implementations:stacksaga-sync/stacksaga-agent/overview/stacksaga-agent.adoc[agent-service] +
The dependency that should be added to the agent-service depends on which database support dependency is used in the orchestrator-service.
For instance, if you are using stacksaga-mysql-support in the orchestrator-service, you need to add stacksaga-agent-mysql dependency to the agent-service.
* If you are using stacksaga-kafka framework(asynchronous implementation), mainly you need to add the dependencies to the flowing services,
** orchestrator-service +
In the orchestrator-service, you need to add three main dependencies as follows,
**** xref:implementations:stacksaga-kafka/stacksaga-starter/overview.adoc[stacksaga-kafka-spring-boot-starter]
**** xref:stacksaga-database-support:overview/database-support-overview.adoc[stacksaga-database-support] (you can choose any one of the database support modules as per your primary database)
**** xref:stacksaga-environment-support:overview/stacksaga-environment-support.adoc[stacksaga-environment-support] (you can choose any one of the environment support modules as per your deployment environment)
** xref:implementations:stacksaga-kafka/agent/overview/stacksaga-kafka-agent.adoc[agent-service] +
The dependency that should be added to the agent-service depends on which database support dependency is used in the orchestrator-service.
For instance, if you are using stacksaga-mysql-support in the orchestrator-service, you need to add stacksaga-kafka-agent-mysql dependency to the agent-service.
** client-service(target-service) +
In the client-service(target-service), you need to add the xref:implementations:stacksaga-kafka/stacksaga-kafka-client/overview.adoc[stacksaga-kafka-client] dependency to be able to consume the messages and send the response back to the orchestrator-service with stacksaga specifications.


IMPORTANT: xref:stacksaga-database-support:overview/database-support-overview.adoc[stacksaga-database-support] and xref:stacksaga-environment-support:overview/stacksaga-environment-support.adoc[stacksaga-environment-support] can be used for both stacksaga and stacksaga-kafka frameworks as a shared module.
for instance, if you are using stacksaga-framework(synchronous implementation) and stacksaga-kafka-framework(asynchronous implementation) in your project together, you can use the same stacksaga-database-support and stacksaga-environment-support modules for both.

