name: Workflow01
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
       - name: Checkout to repository
         uses: actions/checkout@v3
  trigger-workflow02:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow02
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACTIONS_KEY }}
          repository: stacksaga/stacksaga-docs-tool
          event-type: trigger-workflow02
